### ISSUE TITLE
Remove unused material-ui icons from our js bundle

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1003]
`webpack-bundle-analyzer` revealed that a huge part of the js bundle we send to the client is material-ui icons. Since we are only using about 5 of these it appears that the whole set of icons is being sent unnecessarily. Fixing this should drastically improve performance.

![screen shot 2018-08-23 at 4 35 37 pm 2](https://user-images.githubusercontent.com/5498428/44592883-d7f32c00-a78f-11e8-888a-c7d89b214a98.png)

**Comment by smcmurtry** [comment]
Here is some relevant discussion of this issue:

https://github.com/mui-org/material-ui/issues/10857
https://github.com/mui-org/material-ui/issues/11281#issuecomment-389932873

**Comment by alex996** [comment]
@smcmurtry I believe you might also need to add one for `@material-ui/core/styles` or `@material-ui/core/colors`, if either is being used. I tried to tree shake by targeting `@material-ui/core` alone, and it did _not_ affect an import like this: `import { createMuiTheme } from '@material-ui/core/styles'`.
