### ISSUE TITLE
Change material-ui import statements so we only import the components we need

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1004]
See: https://github.com/mui-org/material-ui/issues/7304

This was identified as an issue because `webpack-bundle-analyzer` showed that our common js bundle includes many components from material-ui that we aren't using:
![screen shot 2018-08-30 at 11 35 14 am 2](https://user-images.githubusercontent.com/5498428/44862529-db335f80-ac48-11e8-964c-e5edc5d77ece.png)

**Comment by smcmurtry** [comment]
I tried changing all material-ui import statements from:
`import { Grid } from "@material-ui/core";`

to:
`import Grid from "@material-ui/core/Grid";`

And there was no change I could detect in the common js bundle. Let's investigate this further in the future.

**Comment by sastels** [comment]
Tree shaking seems to be working now - can we close this?

(or, at least, is the remaining bits we care about the icons as discussed in #1277 )

**Comment by smcmurtry** [comment]
Closing this since we're not using material-ui much any more

**Comment by evgeny-s** [comment]
@smcmurtry , is it exists a lightweight alternative to material-ui?
Thank you in advance.
