### ISSUE TITLE
Add Google Analytics Event tracking

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#101]
We should figure out which events to track in GA. ex. What services were selected

**Comment by leonL** [comment]
Optimize for events that we should track during the apps use by The VAC Working Group.

**Comment by leonL** [comment]
The first step is for Dan to decide on what should be captured. (Dan please don't close the ticket. We can use it to track the implementation after you're ready instead)

**Comment by danprime** [comment]
Things/Events to be captured

- Language (English/French)

- Filter Combinations clicked (so for a given session, which filters/values did the user click on)
	- it would be great if we could also send an event with the values of the number of resulting benefits, even better would be extra information as to which benefits were displayed)
Exit/Drop Off Event (did the user click on the final benefit tab)

Comprehension:
Adding buttons at the footer with a label "Did you find the information you're looking for: Y/N" to register Y/N

**Comment by maxneuvians** [comment]
Added Feedback bar in #191 and we are tracking language changes already

**Comment by maxneuvians** [comment]
Closed for now with #272
