### ISSUE TITLE
Cache benefits in memory for initial render

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#107]
The initial render of the app should pull the information out of an in-memory cache vs pulling it from the data store. Subsequent client side requests can go to the data store.

**Comment by sastels** [comment]
Do you mean having it cached on the server?

**Comment by maxneuvians** [comment]
Correct - notice how if you load https://vacpoc.azurewebsites.net/A1 you have a two second delay between the two last items showing? That should not be as well as requests to server should be cached with a TTL on the keys.

**Comment by maxneuvians** [comment]
check out https://github.com/Wizcorp/node-localcache

**Comment by maxneuvians** [comment]
Closed in #174 and #163
