### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#109]
Ran our packages through snyk.io and we need to put an automated process in place as well as fix the existing vulnerabilities. (Currently upgrading next.js)

**Comment by maxneuvians** [comment]
Next.js is currently at 5.1 which has the vulnerabilities.

**Comment by maxneuvians** [comment]
Need to upgrade 5.1 -> 6 and Babel 6 -> 7

**Comment by sastels** [comment]
@maxneuvians should we still do this?

**Comment by maxneuvians** [comment]
Closed in #234
