### ISSUE TITLE
Reset button toggle broken

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1092]
Reset doesn't toggle checks in filter by category :bug:

To reproduce click any options in Filter by Category. 
Then click reset.

**Comment by sastels** [comment]
Good catch! 
This might have started when we switched to check boxes? Looks like internally the filters are cleared (ie we get back to "Showing all benefits") but the actual check mark in the check box gets out of sync with the internal state.
