### ISSUE TITLE
Guided Experience: Make padding consistent with designs

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1098]
![screen shot 2018-09-04 at 11 32 34 am](https://user-images.githubusercontent.com/5498428/45041511-7b68fa00-b036-11e8-9873-98966b78faf2.png)

**Comment by thomascraig** [comment]
Is the blurb under the heading a new feature?  I do not get it when going thru the guided experience @smcmurtry
