### ISSUE TITLE
Tweak Benefit Card headers and footers

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1107]
Benefit card top and bottom attachments should look like part of the card themselves. Currently you can see a part of the rounded corners underneath the blue. 

Also bottom should no longer be blue.

**Comment by smcmurtry** [comment]
Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b3e525390e27e2f31bf67d4
