### ISSUE TITLE
Saved Benefits: top banner

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1113]
Make a white banner near the top with back and print buttons

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b560156d4025ae7299f810f

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/8228248/45049083-9134ea00-b04b-11e8-8fd4-909d50287cb3.png">

**Comment by leonL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Visual Design II](https://trello.com/c/QQbn4GjL/42-update-visual-design-ii)
