### ISSUE TITLE
Saved Benefits empty page

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1118]
tweak page for the case where there are no saved benefits

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b562e457ff49a75561f23b8

<img width="750" alt="image" src="https://user-images.githubusercontent.com/8228248/45050356-11a91a00-b04f-11e8-813d-a0bda3e8bc6e.png">

**Comment by thomascraig** [comment]
@sastels this one already done?
