### ISSUE TITLE
fix learn more button on mobile

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1137]
iPhone 5s via BrowserStack

![image](https://user-images.githubusercontent.com/8228248/45167633-8f903100-b1c7-11e8-9034-6890496c85f2.png)

**Comment by smcmurtry** [comment]
The button no longer breaks in this way, but it does take up 2 lines on narrow screens:
![screen shot 2018-09-19 at 3 36 21 pm](https://user-images.githubusercontent.com/5498428/45776771-ebc06f80-bc21-11e8-8328-c4998f2060a9.png)

**Comment by apmcguigan** [comment]
Remove Button does the same thing, Easiest course of action is to remove the text from the favouriteButton on small screens and to remove the arrow from learn more on small screens. 

Thoughts?

![remove_button](https://user-images.githubusercontent.com/31741286/45777055-18c55000-bc2b-11e8-83f1-89a4bf81f6ff.PNG)

**Comment by sastels** [comment]
👍 good idea!
