### ISSUE TITLE
XSS issues

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#1169]
SAST tool:
+-----------------------------------------------------------------------------------------+
| Severity | Tool | Location |
+-----------------------------------------------------------------------------------------+
| | nodejs_scan | server.js:85 |
| |
| XSS - Reflected Cross Site Scripting |
+-----------------------------------------------------------------------------------------+

**Comment by sastels** [comment]
Huh, that’s the URL validation code, what’s git blame have to say about that? 😛

**Comment by maxneuvians** [comment]
It blames me!

**Comment by maxneuvians** [comment]
Based on

https://www.owasp.org/index.php/Testing_for_Reflected_Cross_site_scripting_(OTG-INPVAL-001)

https://github.com/cds-snc/vac-benefits-directory/blob/master/utils/url_check.js#L11

This should mitigate the vector - but let us discuss in person.

**Comment by ghost** [comment]
Please ping me when you have this chat. Would like to join.
