### ISSUE TITLE
Page is unresponsive after clicking 'print this page'

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1170]
1. Be on this page: https://cdsvacpoc.azurewebsites.net/favourites?lng=en&sortBy=relevance
2. Click 'print this page'
3. Observe a new tab opens with the print menu open. Do not click print or cancel - leave it open. 
4. Navigate back to the original tab you were on. 
5. Click 'back to directory', observe the page is not responding. 
Expected the page would respond even though the print option is open in the new tab. 

(after you close the print tab, the app responds as expected).

**Comment by sastels** [comment]
This is probably a duplicate of #429, which I’m not sure why we closed. I think we decided that it was the browser that was locking things up, not the app? @smcmurtry @maxneuvians ? Regardless, we should do something, as it makes the user get to a state where the app is not responding.

**Comment by sastels** [comment]
one option is to do the print in the same tab as the app (Ie not a new tab) then there’s no app to get stuck in. Breaks the user out of the flow, though.

**Comment by brdunfield** [comment]
Print is currently happening on the same tab. Can this be closed?

**Comment by courtneycl** [comment]
yup!
