### ISSUE TITLE
Veteran and Family Well-Being Fund no 'needs' in air table

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1171]
The Veteran and Family Well-Being Fund does not adhere to any filter rules. It displays on
- Veterans or serving members
- Family members
- Organizations

Unless you apply a filter by category. Then it filters out on all three.
I believe it is supposed to display under Organizations only.

------
To be eligible, you must be a:

Non-profit organization; or
For-profit organization (provided that the nature and intent of the activity is non-commercial, not intended to generate profit, and supports program priorities and objectives); or
Research organizations/institute; or
Educational institution; or
Public health and social services institution; or
Indigenous organization.

**Comment by arothmel** [comment]
Possible duplicate of #653

**Comment by sastels** [comment]
Yeah, exactly right, the problem here I’m pretty sure is that there’s no category / need associated with several Organization benefits.

**Comment by brdunfield** [comment]
Is this still an issue? The example issue seems to be displaying under organizations only for me.

**Comment by smcmurtry** [comment]
Yes this is working as expected - it displays if no selections are made, and if organization is selected. It  doesn't have needs associated because we decided not to use needs for the org benefits.
