### ISSUE TITLE
Career Impact Allowance Supplement is displaying without Career Impact Allowance

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1172]
My selection: Veterans or serving members
Service type: Canadian Armed Forces
Veteran Service status: Still-serving

Issue: Career Impact Allowance Supplement is displaying without Career Impact Allowance. 
-------------
CIA:
You may qualify if you have:

a severe and permanent impairment for which you have received a disability benefit, and
a VAC-approved application for rehabilitation services.
---------------
CIA supplement:
Veterans who receive the Career Impact Allowance, and who are deemed to have diminished earning capacity, are also eligible for the career impact allowance supplement.

**Comment by sastels** [comment]
So the issue is that in our data Career Impact Allowance is restricted to released CAF members, but the supplement is available to all CAF members (!) I’ll get this sorted. Thanks for pointing this out!

**Comment by sastels** [comment]
Thanks for the help sorting this one out @arothmel . For now I've moved CIA to have the same eligibility path as CIAS, ie service member / CAF / has health issue (so both show up for released or still serving members)
