### ISSUE TITLE
Increase benefit card padding to 35px

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1188]
Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b560156d4025ae7299f810f

**Comment by leonL** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Visual Design II](https://trello.com/c/QQbn4GjL/42-update-visual-design-ii)
