### ISSUE TITLE
Show alert if cookies are disabled

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1209]
re: https://trello.com/c/hcVloaHo/17-user-understands-what-limitations-they-have-if-their-cookies-are-disabled-and-how-to-turn-them-on

detect if cookies are disabled. If so,
- notify user of what the consequences are (possibly a banner)
- save this info to redux

**Comment by sastels** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User understands what limitations they have if their cookies are disabled and how to turn them on](https://trello.com/c/hcVloaHo/17-user-understands-what-limitations-they-have-if-their-cookies-are-disabled-and-how-to-turn-them-on)

**Comment by smcmurtry** [comment]
Benefits directory design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b758c1e04618a550dec9617

Favourites design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b562e457ff49a75561f23b8
