### ISSUE TITLE
Change sort by dropdown

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1214]
<img width="227" alt="screen shot 2018-10-02 at 10 28 00 am" src="https://user-images.githubusercontent.com/5498428/46355101-249f1200-c62e-11e8-82fc-26ab48f85f0f.png">

**Comment by sastels** [comment]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b45ad8f38da59ab5e754fe3
