### ISSUE TITLE
Evaluate time to interactive

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1216]
What's acceptable? In particular, load time before clicking links works on slow connections.

**Comment by sastels** [comment]
@smcmurtry @brdunfield @SupeDeDupe has our pruning of material ui and tree-shaking solved this problem?

**Comment by SupeDeDupe** [comment]
@sastels we're still using material ui, and I don't really know much about the conversation for removing our use of it. I'm totally open to clarity though 😅

**Comment by smcmurtry** [comment]
@sastels yes I think our performance is much better now because of lower page weight. Lighthouse gives us and 87/100 for performance.
