### ISSUE TITLE
Automate performance measurement 

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1219]
This is so we can see how changes such as `<Link>`s vs `<a>`s will impact performance.

Choose and set up an automated test suite that will give us performance metrics for the app:

-time to interactive for each page
-page load time
-other relevant metrics?
-all of this for different network speeds and mobile device combinations (low end, mid end, high end) 

The google lighthouse audit in Chrome does all this. Maybe there is a library that will automate running these tests?

**Comment by sastels** [comment]
Platform team is dealing with this issue to develop a tool for use in all our projects.
