### ISSUE TITLE
Upgrading to react-i18next v8.0.6 breaks app

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1223]
We'll have to fix this at some point unless we want to be stuck on our current version.

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Technical Debt Sprint 3](https://trello.com/c/Q3bSJUnL/79-technical-debt-sprint-3)

**Comment by brdunfield** [comment]
closed with #1436
