### ISSUE TITLE
Saved Benefits -> BD clears profile selections

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1229]
1) click some profile filters (ie "Family members") and some needs
2) click Saved Benefits link
3) click "Back to directory"
4) profile filters are cleared, needs are not.

they're not in the url, that's probably it.

**Comment by sastels** [comment]
Note that #1217 might fix this issue

**Comment by courtneycl** [comment]
Reopening - seeing this issue again. All selections are cleared when going from Saved List back to directory; expected that they would not be cleared.

**Comment by courtneycl** [comment]
0. Make sure you have no saved benefits 
1. Be on the directory page with some selections enabled, like: 
![image](https://user-images.githubusercontent.com/3474250/50166815-c7723e80-02b5-11e9-86f3-e8089090ebe8.png)
2. Click `Saved list`
3. Click `Return to benefits list` (NOT the breadcrumb)
![image](https://user-images.githubusercontent.com/3474250/50167085-567f5680-02b6-11e9-8583-4e02e3ee9a0a.png)
4. Observe the selections are dropped on the directory page. Expected the selections would still be selected.
