### ISSUE TITLE
Change map height

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1245]
Should be 805px high on desktop: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b59dca4a4fc7a57bc7e3bbd

Should be 230px high on mobile:
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b59dca4a4fc7a57bc7e3bbd

**Comment by sastels** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Visual Design: Mobile](https://trello.com/c/W0Jkw0uS/43-update-visual-design-mobile)
