### ISSUE TITLE
Add tooltip columns to Airtable, add to Guided Experience

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1271]
re https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b758b93a66edd9e97695d0f
https://trello.com/c/UOOkpRyb/14-user-understands-what-a-service-related-health-issue-means

Add English / French Tooltip columns to Airtable, and add to Guided Experience if they contain info

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User understands what a Service-related health issue means](https://trello.com/c/UOOkpRyb/14-user-understands-what-a-service-related-health-issue-means)
