### ISSUE TITLE
[TRANSLATE] appears in French site title 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1290]
![image](https://user-images.githubusercontent.com/3474250/46822646-04700100-cd5a-11e8-8306-ddc32a606c07.png)

**Comment by sastels** [comment]
🙂 this is a feature, not a bug - we do that for any French content that hasn’t been signed off on. Proper translations are put in Airtable (and the TRANSLATE tag removed)

**Comment by sastels** [comment]
(Mind you, getting someone qualified to go through all the tagged strings in Airtable is an important issue, maybe we should add it to Trello product backlog?)
