### ISSUE TITLE
Improve the eligibility airtable

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1296]
It would be better if it was linked to the multipleChoiceOptions table, that way you could have multiple answers linked. That could be replace by the na thing, which is kind of confusing.

**Comment by sastels** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User answers as little profile questions as possible](https://trello.com/c/MF0pMzGT/20-user-answers-as-little-profile-questions-as-possible)
