### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1301]
Currently we search by or-ing the search results per search term together, then sort the list by either popularity or alphabetical. We should probably either

* ~~require all the search terms~~
* sort by search score

**Comment by courtneycl** [comment]
@sastels do you suspect this work will be covered in https://trello.com/c/Q1jpikL1/13-users-are-able-to-use-familiar-keywords-needs-to-search-for-relevant-benefits ?

**Comment by sastels** [comment]
yes (this issue was originally more of a placeholder).

I've updated this issue to reflect that we're going to sort the searched benefits by sort score.

**Comment by smcmurtry** [comment]
We're now sorting by search score
