### ISSUE TITLE
Health Care Benefits card: RCMP not eligible for Disability Award 

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1314]
When following the eligibility path for RCMP.
Info: You need to be approved for Disability Award or Disability Pension before applying for Health Care Benefits.
RCMP not eligible for Disability Award

**Comment by sastels** [comment]
Right now the info header is the same regardless of the user (even if, as you have discovered, they're not eligible for all the gateway benefits mentioned). @sidewalkballet @michellengaiCDS have we given any thought to user testing the headers, ie is this situation confusing to users?

**Comment by courtneycl** [comment]
We can chat with Mithula about this when she's back. Might be worth adding to a test plan with RCMP members. 

@arothmel do you know if there are other instances of this kind of thing?

**Comment by sastels** [comment]
Currently the child benefits in the footer are not filtered either.

**Comment by leonL** [comment]
@arothmel please migrate this issue to one of our Trello boards.
