### ISSUE TITLE
Janky Data Validation page?

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1336]
Data validation page was complaining about empty rows in a table. It was right! I deleted the empty rows and refreshed AirTable. Data validation still complains about the (now nonexistent) empty rows. Changed a benefit name and refreshed, that change made it into the app.

![image](https://user-images.githubusercontent.com/8228248/47234322-74f2cf80-d3a3-11e8-8545-9aa8d388b136.png)

**Comment by smcmurtry** [comment]
This no longer seems to be a problem: 
![Screen Shot 2019-03-18 at 2 18 49 PM](https://user-images.githubusercontent.com/5498428/54553558-d8038500-4988-11e9-927b-bc27c2dc6561.png)
