### ISSUE TITLE
ARIA role="complementary" should not be assigned to our <noscript> element

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1347]
From Level Access:

[Issue]
An ARIA role="complementary" attribute is assigned to an element on an invalid element.

[Impact]
Assistive technology will not properly identify this region as complementary to the main content as intended.

[Code Sample]
```
<noscript role="complementary">
<div class="css-1wjadmq e5xum6a0">
<div class="css-v6xgob e5xum6a1">
<div class="copy">
<p>Javascript is disabled and you may experience reduced functionality. To see a full list of benefits, click<a href="/all-benefits">here</a>.
</p>
</div>
</div>
<div class="css-qiebqe e5xum6a2"></div>
</div>
</noscript>
```

[Expected Behavior]
Ensure that role="complementary" is only used on elements that allow the attribute.

Reference:
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/complementary.html

**Comment by sastels** [comment]
This was fixed in #1179 (Axe started complaining about the same issue)
