### ISSUE TITLE
Profile questions path for family members not correct

### ISSUE THREAD

**Issue by michellengaiCDS** [veteransaffairscanada/vac-benefits-directory#1353]
When a user selects "Benefits for family members" and then selects "RCMP" as the service type, they should not be seeing the Status or Service-related health issue questions after.

**Comment by courtneycl** [comment]
related - #1339

**Comment by sastels** [comment]
@michellengaiCDS Currently (probably changed since you filed the issue) we do not show the health issue question. We do show the status question - if the Veteran has passed away than the family may be eligible for the Survivor's Pension.

**Comment by smcmurtry** [comment]
Closing this since a user selecting Family + RCMP doesn't see the health issue question.
