### ISSUE TITLE
When navigating the page via keyboard, visual keyboard focus is lost within the map

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1358]
From Level Access:

Ensure keyboard focus is indicated visually

[Issue]
When navigating the page via keyboard, visual keyboard focus is lost within the map.

[Impact]
Assistive technology users may have difficulty determining where they are on the page.

[Expected Behavior]
Ensure that visual keyboard focus is always present on interactive elements. Developers should ensure that a distinct indication of focus, such as a prominent border, is displayed for all active elements.

**Comment by brdunfield** [comment]
I think #1641 falls under this

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)

**Comment by smcmurtry** [comment]
Closing since we no longer have a map page.
