### ISSUE TITLE
Swap out material-ui radio button component for gov.uk one

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1362]
This will make it easier to have a consistent focus style across all components. And it should also fix the broken keyboard navigation that exists for our current radio component.

https://github.com/UKHomeOffice/govuk-react

**Comment by brdunfield** [comment]
Now the #1344 is implemented, is keyboard navigation still broken? Is this now purely a style issue?

**Comment by smcmurtry** [comment]
Yeah it's still broken. If you are focused on a selected option in the first radio group on the benefits directory, pressing tab doesn't take you to the next radio group, it skips over it.

**Comment by brdunfield** [comment]
That might be a different issue, it looks as though the different radio lists are linked in some way based on how the navigation is happening.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility work](https://trello.com/c/H7Q1Ycrm/93-accessibility-work)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Screenreader Navigation](https://trello.com/c/knKtuM4T/100-accessibility-screenreader-navigation)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Screenreader Navigation](https://trello.com/c/knKtuM4T/100-accessibility-screenreader-navigation)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)
