### ISSUE TITLE
Searching on the map page doesn't change the map view to the search location

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1364]

**Comment by sastels** [comment]
It does for me?
1) type "bangkok" in search bar. hit return
2) map zooms to Thailand. nearest office is St. John's 15130km away (admittedly, a bit off)

**Comment by brdunfield** [comment]
This works for me as well, unless I misunderstood the issue.

**Comment by sastels** [comment]
@smcmurtry ☝️ ?

**Comment by smcmurtry** [comment]
Looks like this is either fixed or maybe it was never broken in the first place 🤔
