### ISSUE TITLE
"title" variant of div?

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1371]
WebStorm complains about `profile_needs_selector.js`

<img width="295" alt="image" src="https://user-images.githubusercontent.com/8228248/47501857-7ead8480-d834-11e8-9b8d-9ed9fdeeec55.png">

**Comment by brdunfield** [comment]
If I remove the variant tag, it doesn't look like anything on the page changes.. I'm not sure if it's there for another reason though.

**Comment by smcmurtry** [comment]
Closing since we no longer have a `ProfileNeedsSelector` component.
