### ISSUE TITLE
user can input Airtable base key

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1382]
* Add on the data validation page an input so the user can change the AirTable base (ie, to a staging copy of Master). 
* When the input fires it will have to tell the server what the new base is (probably via the current `refresh` post). 
* Have a environment variable to enable this feature (so that by default, ie on the master app, the input box doesn't appear, and the refresh doesn't user a base even if it's passed

**Comment by smcmurtry** [comment]
I think we no longer need to do this since we've gone with a different model for content staging - 1 app that is tied to 1 instance of airtable, so no need for an admin user to reconfigure this.
