### ISSUE TITLE
Remove unused rows from the translation table in airtable

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1394]
There are many rows that we were using at one point, but aren't using now. This could be done by searching our codebase for the the id, and deleting the row if no id is found.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve the Airtable admin experience](https://trello.com/c/Ca0kPfYH/94-improve-the-airtable-admin-experience)

**Comment by apmcguigan** [comment]
Would it be worth adding something into the data-validation page for this? So it lets us know if something in a table is not being used.

**Comment by SupeDeDupe** [comment]
Deleted unused rows from translation sheet in Airtable.

Closes #1394
