### ISSUE TITLE
Headings are out of order in DOM on benefits-directory page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1405]
Using keyboard navigation to go through the benefits-directory page follows DOM order. Currently you get to an h2 before the h1, which is a problem. I'm not sure how to fix this because with side by side grid containers, the thing on the left is first in the DOM order.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility work](https://trello.com/c/H7Q1Ycrm/93-accessibility-work)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Screenreader Navigation](https://trello.com/c/knKtuM4T/100-accessibility-screenreader-navigation)

**Comment by SupeDeDupe** [comment]
Might be a useful source for this issue:

https://medium.com/@Heydon/managing-heading-levels-in-design-systems-18be9a746fa3

**Comment by brdunfield** [comment]
https://stackoverflow.com/questions/4112289/what-is-the-html-tabindex-attribute
