### ISSUE TITLE
First back button in Guided Experience needs 2 clicks

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1421]
If a radio item is set, for this screen only, navigating back takes too clicks.

See #1408 for more info.

**Comment by brdunfield** [comment]
I believe this bug is still present, but it is very difficult to test as the initial back button currently doesn't go anywhere, but will eventually link back to the VAC homepage.

**Comment by smcmurtry** [comment]
I switched the link to the VAC home page in airtable and the button is now working as expected with 1 click.
