### ISSUE TITLE
Duplicate text next to beta banner

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1427]
How to recreate:
(Possibly only in Chrome)
1) Click the app's French button.
2) Reload the webpage after the translation has been changed.
3) On the Google pop-up that asks to translate the page to English, click the Translate button.
4) Click the app's English button.

<img width="509" alt="screen shot 2018-11-13 at 10 56 43 am" src="https://user-images.githubusercontent.com/17673146/48436976-8a66d980-e756-11e8-9955-81a74883ffc2.png">
<img width="1434" alt="screen shot 2018-11-13 at 10 59 26 am" src="https://user-images.githubusercontent.com/17673146/48436992-92bf1480-e756-11e8-8cc8-587da0844cb6.png">
<img width="1437" alt="screen shot 2018-11-13 at 1 10 49 pm" src="https://user-images.githubusercontent.com/17673146/48436996-96529b80-e756-11e8-9971-a72b189f1e53.png">

**Comment by smcmurtry** [comment]
I don't think we need to do anything about this. If the user wants the page translated, they can either use our translate button or google translate, but not both.
