### ISSUE TITLE
Remove the sort by dropdown

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1444]
We should always sort by the priority column in airtable, then alphabetically, unless the user has entered text in the search box. Because we will always be setting this programmatically, we can remove the sort by dropdown from the app.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User sees benefits listed by relevance to search term](https://trello.com/c/Kl9anbsX/101-user-sees-benefits-listed-by-relevance-to-search-term)

**Comment by SupeDeDupe** [comment]
Is this just completely removing the sort by dropdown from the app?
