### ISSUE TITLE
Implement Share Button and modal

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1452]
Copy link to clipboard.

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are able to copy the URL and share to their networks](https://trello.com/c/q8cZ0odM/102-users-are-able-to-copy-the-url-and-share-to-their-networks)

**Comment by smcmurtry** [comment]
Closed by #1453
