### ISSUE TITLE
Header bar render issue

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1460]
happens when the app with a query string is loaded, but does not happen if page is navigated to from home page.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are able to copy the URL and share to their networks](https://trello.com/c/q8cZ0odM/102-users-are-able-to-copy-the-url-and-share-to-their-networks)
