### ISSUE TITLE
Add Share Modal translations to AirTable

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1464]

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are able to copy the URL and share to their networks](https://trello.com/c/q8cZ0odM/102-users-are-able-to-copy-the-url-and-share-to-their-networks)

**Comment by courtneycl** [comment]
When doing this can you make `Share this Page` sentence case to match the rest of the app?
