### ISSUE TITLE
Add a "Skip" button to Guided Experience Questions

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1465]

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are able to skip through guided experience questions](https://trello.com/c/P2jB4luJ/107-users-are-able-to-skip-through-guided-experience-questions)

**Comment by smcmurtry** [comment]
Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b758b93a9329e48562a94d7

**Comment by smcmurtry** [comment]
Closed by #1484
