### ISSUE TITLE
Guided Experience Summary Page

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1467]
Indicates selected answers or which questions were skipped.

![image](https://user-images.githubusercontent.com/5032149/49029438-99945100-f172-11e8-865c-1d9c7b416e43.png)
![image](https://user-images.githubusercontent.com/5032149/49029351-5c2fc380-f172-11e8-8518-7311c4c78290.png)
![image](https://user-images.githubusercontent.com/5032149/49029493-bfb9f100-f172-11e8-8b15-5ecca0debbdd.png)
![image](https://user-images.githubusercontent.com/5032149/49029536-d7917500-f172-11e8-8490-fab12dba2bac.png)

**Comment by smcmurtry** [comment]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5bf485af03298f5a1d6a092a

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The product clearly communicates what it will provide for users](https://trello.com/c/IvBGfhjz/105-the-product-clearly-communicates-what-it-will-provide-for-users)

**Comment by smcmurtry** [comment]
I broke this up into some smaller issues: #1485, #1486, #1487, #1488
