### ISSUE TITLE
Remove breadcrumbs from GE

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1481]
This functionality is moving to the summary page.

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/dashboard

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The product clearly communicates what it will provide for users](https://trello.com/c/IvBGfhjz/105-the-product-clearly-communicates-what-it-will-provide-for-users)

**Comment by SupeDeDupe** [comment]
Can we maybe add putting the breadcrumbs in the summary onto this issue? I think some stuff happening with breadcrumbs is reusable or could at least be used as a base idea on how to do it in the summary page, so maybe these 2 things should be done at the same time.

**Comment by smcmurtry** [comment]
@SupeDeDupe good point! I think we should keep them as separate issues but do this one after the the links are added to the summary page.

**Comment by SupeDeDupe** [comment]
👍
