### ISSUE TITLE
Implement a see more / see less button and move child benefits

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1505]
Also remove the existing expansion panel:

![screen shot 2018-11-29 at 5 02 12 pm](https://user-images.githubusercontent.com/5498428/49254923-96aa9200-f3f8-11e8-8b31-1d95f96ce533.png)
![screen shot 2018-11-29 at 5 02 05 pm](https://user-images.githubusercontent.com/5498428/49254924-97432880-f3f8-11e8-9a36-b78f0d364f82.png)

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users see exactly what benefits can provide for them](https://trello.com/c/sz3HfuNZ/95-users-see-exactly-what-benefits-can-provide-for-them)

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User is overwhelmed viewing the directory for the first time after going through the guided experience](https://trello.com/c/MM7hS6SQ/113-user-is-overwhelmed-viewing-the-directory-for-the-first-time-after-going-through-the-guided-experience)
