### ISSUE TITLE
Add edit icons to summary page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1518]
Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5bf485af03298f5a1d6a092a

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The product clearly communicates what it will provide for users](https://trello.com/c/IvBGfhjz/105-the-product-clearly-communicates-what-it-will-provide-for-users)
