### ISSUE TITLE
App should jump to top of page when moving between pages 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1528]
When moving between pages of the app, the app remains scrolled to where you were on the previous page. Expected it would jump to the top. 

Repro:
1. On the first page of the app, scroll down, then hit next: 
![image](https://user-images.githubusercontent.com/3474250/49447360-b6510a00-f7ac-11e8-8ea7-83b64ac1cc74.png)
2. Observe that the next page is scrolled down too: 
![image](https://user-images.githubusercontent.com/3474250/49447370-bcdf8180-f7ac-11e8-8831-c3e4882f2588.png)

This is very obvious when it's the last page:
![image](https://user-images.githubusercontent.com/3474250/49447459-ff08c300-f7ac-11e8-8f9c-90c91ffae20b.png)
hit results:
![image](https://user-images.githubusercontent.com/3474250/49447470-0760fe00-f7ad-11e8-9650-59ed314aad0a.png)

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The product clearly communicates what it will provide for users](https://trello.com/c/IvBGfhjz/105-the-product-clearly-communicates-what-it-will-provide-for-users)
