### ISSUE TITLE
Going back to edit a skipped question causes you to re-enter the full GE journey at that q 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1529]
Example for repro: 
1. Start the guided experience, select `Benefits for Veterans`, hit next
2. Skip the second question on service type to end up on the categories page
3. Pick a couple categories and hit next so your results look like this: 
![image](https://user-images.githubusercontent.com/3474250/49451259-2cf20580-f7b5-11e8-9b7c-953bc1917873.png)
4. Hit the pencil icon next to `Service type not selected` to edit the field
5. On `Select service type`, select `Canadian Armed Forces`, hit next
6. Select `yes` on health-related issue, hit next
7. Observe you land on an empty `Select the categories of benefits you want to see` page and have to re-enter your previous selections. 

Expected that you would not be shown this page again because you have already entered your selections, and you would return to the `Here are your selections` page.

**Comment by courtneycl** [comment]
This bug might be tricky because if you complete all the selections and then go to edit the benefit recipient from Veterans to Family, the subsequent q's change and you _do_ need to go through the subsequent questions over again. 

I think it comes down to: if you already selected categories, don't show the categories page again OR we change the design to tell the user to start over entirely rather than give the expectation that they're editing a single selection when they actually have to edit more. 

cc @michellengaiCDS

**Comment by michellengaiCDS** [comment]
I think it's okay to still show the categories page again as long as all their previous selections are still there. Right now, it completely resets.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The product clearly communicates what it will provide for users](https://trello.com/c/IvBGfhjz/105-the-product-clearly-communicates-what-it-will-provide-for-users)

**Comment by SupeDeDupe** [comment]
Two things to implement here:
1) Change the way questions are being cleared.  Only clear questions that no longer appear on the current path.
2) Next button should go to the next unanswered question on the current path.
