### ISSUE TITLE
Move share and print buttons to sidebar

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1536]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c006920d385f82c6d6bafaa

<img width="1115" alt="screen shot 2018-12-05 at 3 17 21 pm" src="https://user-images.githubusercontent.com/17673146/49538057-e974c580-f8a0-11e8-812d-84a1d4056d18.png">

**Comment by brdunfield** [comment]
Looks like this is a more up-to-date #1509 . I will close #1509
