### ISSUE TITLE
move and change styling of favourites link, add blue box around edit dropdown

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1544]
Don't implement the red circle for now or the new icon, but include the number of saved benefits in the button text.

Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c006920d385f82c6d6bafaa

<img width="209" alt="screen shot 2018-12-06 at 2 23 48 pm" src="https://user-images.githubusercontent.com/5498428/49603806-a4b16300-f962-11e8-96e7-006a2c10f40f.png">

**Comment by brdunfield** [comment]
It's easiest I think for me to just implement this alongside #1536 in the interests of keeping the app looking more finished between PRs.
