### ISSUE TITLE
Add dynamic content to Next Steps

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1549]
I think this one is waiting on design specifications with how the dynamic content will function, as well as the content itself.

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c0967a90325f0b832027f22
<img width="589" alt="screen shot 2018-12-06 at 3 56 01 pm" src="https://user-images.githubusercontent.com/17673146/49608610-738b5f80-f96f-11e8-801f-ca009ab8b364.png">

**Comment by brdunfield** [comment]
More specific issues created
