### ISSUE TITLE
Add Next steps component and scroll button to Favourites page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1554]
Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c006921d385f82c6d6bb073

<img width="990" alt="screen shot 2018-12-07 at 8 54 49 am" src="https://user-images.githubusercontent.com/5498428/49648869-cd3a6b00-f9fd-11e8-960f-76396aa6a708.png">

**Comment by brdunfield** [comment]
This was also done in #1559 , oops!
