### ISSUE TITLE
Reset button should be at top of selection pane 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1556]
Reset button is at the bottom, well below the scroll and easy to miss. We should move it to the top, underneath Edit selections. 

![image](https://user-images.githubusercontent.com/3474250/49650141-af6f0500-fa01-11e8-8e5c-da05b7184890.png)

move; 
![image](https://user-images.githubusercontent.com/3474250/49650151-b7c74000-fa01-11e8-932c-c1054ee88c34.png)

**Comment by SupeDeDupe** [comment]
I believe the consensus from last week is that we're waiting on the design images to change this. There's no current design available for the filter dropdown. @smcmurtry

**Comment by smcmurtry** [comment]
@SupeDeDupe I think it's okay - this will make the reset button easier to find.
