### ISSUE TITLE
Make AirTable sheet for What's next Bullets

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1561]

**Comment by smcmurtry** [comment]
Done: https://airtable.com/tbliIHYlkUO3NymW8/viwWq2xotUTzmoirA

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are given options for what the next step is in their current stage](https://trello.com/c/rHNRWLYF/2-users-are-given-options-for-what-the-next-step-is-in-their-current-stage)
