### ISSUE TITLE
Make What's Next bullets dynamic

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1564]
Based on eligibility paths. Initial iteration using "no eligibility requirements" path while we wait on content.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users are given options for what the next step is in their current stage](https://trello.com/c/rHNRWLYF/2-users-are-given-options-for-what-the-next-step-is-in-their-current-stage)
