### ISSUE TITLE
Security Update Sprint T+6

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1570]
Our aim is to update all package dependencies once per sprint. Responsibility for this task is rotated through all the developers. We have come up with the following more or less sane workflow given the the Javascript ecosystem:

In a new branch

- [x]   Prune things no longer needed
- [x]   Run yarn upgrade-interactive --latest --ignore-engines to find upgraded packages
- [x]   Upgrade patch and minor version changes (green and yellow)
- [x]   Run tests
- [x]   Commit

For each red (major version) upgrade:

- [ ]   Upgrade
- [ ]   Run tests
- [ ]   Examine app locally
- [ ]   Commit

**Comment by sastels** [comment]
You can ignore the upgrade of `emotion` to version 10, it's covered by issue #1526

**Comment by SupeDeDupe** [comment]
Closed by #1607
