### ISSUE TITLE
Enlarge Next Steps space when no results

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1578]
The space Next steps is in gets squashed a bit when there are no results:
<img width="1437" alt="screen shot 2018-12-11 at 9 04 37 am" src="https://user-images.githubusercontent.com/17673146/49806068-1dcb0480-fd2d-11e8-9f82-3c035348fe93.png">

<img width="1434" alt="screen shot 2018-12-11 at 9 04 45 am" src="https://user-images.githubusercontent.com/17673146/49806014-fa07be80-fd2c-11e8-8606-b46eafd263b6.png">

**Comment by smcmurtry** [comment]
Closed by #1597
