### ISSUE TITLE
finish emotion 10 upgrade

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1588]
We have partially migrated to emotion 10, following the migration path as described in https://emotion.sh/docs/migrating-to-emotion-10. We have to finish the migration. Essentially, instead of passing the ``css`...` `` using the `className` prop, we should use the `css` prop.

**Comment by brdunfield** [comment]
We may want to hold off on doing this until we upgrade to a version that contains

https://github.com/emotion-js/emotion/pull/1049

Will avoid us having to have a jsx pragma at the top of every file

**Comment by tkh44** [comment]
FWIW it was released last night. https://www.npmjs.com/package/@emotion/babel-preset-css-prop

**Comment by brdunfield** [comment]
#1617 was a first attempt, but is shaping up to be too much work to be worth it this sprint. We should revisit this later as per the closing comment in the PR.
