### ISSUE TITLE
Sidebar stays fixed when page is scrolled

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1618]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3f78b6172da20dd1233d52

<img width="963" alt="screen shot 2019-01-17 at 1 54 30 pm" src="https://user-images.githubusercontent.com/17673146/51338138-6e85f980-1a5f-11e9-9e67-a156bb8d1a31.png">

**Comment by smcmurtry** [comment]
Closing until this feature is designed and ready to be worked on

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar remains fixed on the side when list of benefits is scrolled](https://trello.com/c/vXnIGGiA/132-sidebar-remains-fixed-on-the-side-when-list-of-benefits-is-scrolled)

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar remains fixed on the side when list of benefits is scrolled](https://trello.com/c/vXnIGGiA/132-sidebar-remains-fixed-on-the-side-when-list-of-benefits-is-scrolled)

**Comment by brdunfield** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar remains fixed on the side when list of benefits is scrolled](https://trello.com/c/vXnIGGiA/132-sidebar-remains-fixed-on-the-side-when-list-of-benefits-is-scrolled)
