### ISSUE TITLE
Move 'vous' to second line on FR trouvez un bureau 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1633]
The French translation puts the arrow below the text and it doesn't look great - ~~can we make the boxes a bit wider to accommodate?~~ move `vous` onto the second line (per [Michelle](https://github.com/veteransaffairscanada/vac-benefits-directory/issues/1633#issuecomment-449468204))

![image](https://user-images.githubusercontent.com/3474250/50250160-0d123280-03ae-11e9-9caf-eac9f10c4cba.png)

**Comment by SupeDeDupe** [comment]
@sidewalkballet is that the final translation?

**Comment by brdunfield** [comment]
It looks like these boxes are sized to match the content above. A couple options:
- Make the left box slightly thinner
- Reduce the font size of the title
- Add a non-breaking space after vous so that both vous and the arrow are pushed to the second line (potentially my recommended option)

**Comment by courtneycl** [comment]
> @sidewalkballet is that the final translation?

@SupeDeDupe yes

**Comment by courtneycl** [comment]
@michellengaiCDS any preferences on Bethany's solutions?

**Comment by michellengaiCDS** [comment]
Thanks for the options Bethany! Let's go with your recommended - moving the "vous" down as well so the arrow isn't so lonely. Thanks!
