### ISSUE TITLE
Radio button groups get combined in the benefits directory filters

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1640]
When using VoiceOver, it perceives the separate button groups as a single group. Tab functionality also behaves as if they are a single group. This makes it difficult to navigate with Tab and understand with VoiceOver
![screen shot 2018-12-20 at 11 47 53 am](https://user-images.githubusercontent.com/5032149/50298473-38982a00-044d-11e9-9702-c124af92f5e2.png)

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Screenreader Navigation](https://trello.com/c/knKtuM4T/100-accessibility-screenreader-navigation)
