### ISSUE TITLE
Benefit order changes when switching EN -> FR 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1650]
1. Be on the EN directory, no selections, observe Disability Award is listed first: 
![image](https://user-images.githubusercontent.com/3474250/50603450-83239880-0e88-11e9-87e2-42f47d002bb2.png)
2. Switch to FR, observe Avantages pour soins de santé is listed first: 
![image](https://user-images.githubusercontent.com/3474250/50603479-99c9ef80-0e88-11e9-9294-94cbb5def2c5.png)

Expected the sort order would be the same for both langs; L'indemnité d'invalidité would be first.

**Comment by brdunfield** [comment]
This is because they are sorted alphabetically. We should discuss what other options are for sorting the benefits if the goal is to preserve the order across languages.

**Comment by courtneycl** [comment]
Ah ok, it looks like there's three priority groups in Airtable and they sort A-Z within them (I think I remember @smcmurtry talking about revisiting that?). We've heard a lot from staff that having DA appearing first is good, but if it's high enough, maybe it doesn't matter. @scottlester1 might have an opinion.

**Comment by smcmurtry** [comment]
Closing this since as @brdunfield mentioned this is expected behaviour for the alphabetical sort.
