### ISSUE TITLE
Keyboard navigation after pressing "See More" can be improved

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1652]
When using keyboard navigation, after selecting a "see more" button, the focus is still on the see more button, which is below the content that has just been expanded.

This can be improved somehow.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)
