### ISSUE TITLE
Cards need to be refreshed to show language change

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1671]
If you have already pre-selected filters and then select toggle language English -> Français the cards still display the original language until you hit refresh. This happens when you switch back to English as well. 
All of the other page text translates properly when you click the language button. 
Note: This does not happen if you change language before selecting filters.

To reproduce filter on benefits dir page
Select:
   -- Benefits for family members
   -- Royal Canadian Mounted Police
   -- Release
Click on Français

The cards are still in English until you hit refresh

**Comment by smcmurtry** [comment]
Wow that is an interesting bug. It also happens if you select "veteran, emergency funds"

**Comment by arothmel** [comment]
I recently added a card to "veteran, emergency funds". Is it related? So I checked "veteran, death and bereavement". It does the same thing. Interesting indeed!
