### ISSUE TITLE
Update AirTable structure to more closely resemble Allison's spreadsheet

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1673]
Leave existing columns intact for now so as to not break master.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change eligibility path structure to be more like Allison's spreadsheet](https://trello.com/c/KXov9hiW/148-change-eligibility-path-structure-to-be-more-like-allisons-spreadsheet)

**Comment by brdunfield** [comment]
Created a new benefitEligibility table:
https://airtable.com/tblRNTYbp9OWDSj4l/viwB7uV1iu2dCaa5P

**Comment by brdunfield** [comment]
Closed as part of #1694
