### ISSUE TITLE
The benefit-directory has a horizontal scroll

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1684]
Not sure what element is exceeding the screen width and causing this

**Comment by brdunfield** [comment]
Also seems to be present on the summary and map pages

**Comment by apmcguigan** [comment]
As far as I can tell it's present on every page. So it might be tied to some universally used high level component

**Comment by brdunfield** [comment]
@apmcguigan I figured it out! it's the skip to main content div I recently added. Should just need some styling changes to remove the excess margin / padding or whatever is conflicting.
