### ISSUE TITLE
Inconsistent display of text for 'My VAC Account'  

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1689]
There are two instances of My VAC Account with a lower case 'A'/'a' at the bottom of the benefits directory.
This tends to draw concern during product demo. I hope somebody can just jump in and fix it before the next demo. Was issue #1540 
![image](https://user-images.githubusercontent.com/3801459/51050746-2f136500-15a8-11e9-9e72-3c30e0c2710b.png)

**Comment by apmcguigan** [comment]
I found both of the entries in airtable, is the correct usage account with a capital A?

**Comment by arothmel** [comment]
I didn't realize it was in airtable. My VAC Account is correct. As is Mon dossier ACC

**Comment by arothmel** [comment]
I can do it. Thanks for pointing out how
