### ISSUE TITLE
Use an anchor element for Learn More buttons

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1705]
From John O'Brien:

"On the list of all benefits pages, the green buttons that link out from a particular benefit exhibit.. non-traditional link based behaviours.

1: There is no mouse-over view of the domain in the browser status bar at bottom of page.
2: Right clicking on button does not present the typical (open in..) experience that one expects with an <a href=>

These combined lead to what I would consider is not-recommended experience in that the user
has no way to determine the safety of clicking on the button. "

**Comment by brdunfield** [comment]
Related: #1390
