### ISSUE TITLE
Sidebar scroll doesn't seem to work in IE

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1724]

**Comment by smcmurtry** [comment]
Sidebar does not stick in place at the top of screen on IE.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar remains fixed on the side when list of benefits is scrolled](https://trello.com/c/vXnIGGiA/132-sidebar-remains-fixed-on-the-side-when-list-of-benefits-is-scrolled)

**Comment by smcmurtry** [comment]
Closing this since the new design doesn't have a sticky sidebar, just a sticky header on both desktop and mobile.
