### ISSUE TITLE
Sticky header for mobile in benefits directory

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1726]
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3f8e799f82f718aea01b56
<img width="287" alt="screen shot 2019-01-21 at 3 12 43 pm" src="https://user-images.githubusercontent.com/17673146/51494439-08ff7900-1d8f-11e9-8683-d2523ee0f0a7.png">

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar remains fixed on the side when list of benefits is scrolled](https://trello.com/c/vXnIGGiA/132-sidebar-remains-fixed-on-the-side-when-list-of-benefits-is-scrolled)

**Comment by smcmurtry** [comment]
After some discussion we're just going to have the saved/next steps/edit buttons in the header.
