### ISSUE TITLE
Refactor the code to use a consistent mobile screen size(s)

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1746]
The breakpoints are not all consistent for mobile screens throughout the code. Sometimes `globalTheme.max.xs` is used and sometimes `globalTheme.max.mobile` is used. sm is also used in some spots.

**Comment by smcmurtry** [comment]
I think this has been resolved by adopting the breakpoints from veterans.gc.ca. Is it okay if we close this @SupeDeDupe?

**Comment by SupeDeDupe** [comment]
The code doesn't have much consistency with which size we're using - sometimes it's 399.5px, 424.5px, or 767.5px. This needs to be pruned for consistency.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up code; remove components no longer being used and rename ones that are ambiguous](https://trello.com/c/EctxU3VR/206-clean-up-code-remove-components-no-longer-being-used-and-rename-ones-that-are-ambiguous)

**Comment by SupeDeDupe** [comment]
Closed by #2147
