### ISSUE TITLE
Next steps header should not be displayed if the list is empty

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1755]
![image](https://user-images.githubusercontent.com/17673146/51760038-9b599280-2097-11e9-8ae0-fbc0fed8b068.png)

**Comment by brdunfield** [comment]
Will there ever be a situation where there are no next steps and this needs to be implemented? This behaviour was observed before #1761 fixed a different bug.

**Comment by brdunfield** [comment]
Closed as per discussion in #1778
