### ISSUE TITLE
Non-distinguishable landmarks

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1756]
From Julianna:

Found with Siteimprove:

1.3.1 Info and Relationships
The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained.

Use the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark.

*Code:*

```<div class="css-4kq50w" role="navigation" style="z-index: 2147483646; position: relative;"><div class="jss107 jss109 jss108 css-13t8z2z" style=""><a class="css-wtmo4k" id="privacy" href="https://digital.canada.ca/legal/privacy/" target="_blank" rel="noopener noreferrer" style="">Privacy</a><p class="css-1gp8dje" style="">Build: <!-- -->9890533</p><div class="css-1magkk1" style=""><svg role="img" aria-label="Symbol of the Government of Canada" xmlns="http://www.w3.org/2000/svg" version="1.1" width="6em" height="100%" viewBox="0 0 143 34" preserveAspectRatio="xMinYMin meet" style=""><g id="wmms" transform="translate(-1, -1)" style="">```

*Notes*
This is an error occuring when role="navigation" is present.

*How do I meet this criteria?*
Use one of the following techniques from WCAG 2.0:

ARIA13 Using aria-labelledby to name regions and landmarks

**Comment by brdunfield** [comment]
<img width="1358" alt="screen shot 2019-03-04 at 2 53 42 pm" src="https://user-images.githubusercontent.com/5032149/53759031-62c68900-3e8d-11e9-85d2-c6d62ffbdbb1.png">
<img width="1358" alt="screen shot 2019-03-04 at 2 53 59 pm" src="https://user-images.githubusercontent.com/5032149/53759032-62c68900-3e8d-11e9-97bc-54e035a8f236.png">

I will flag these to design and see what they say.

**Comment by brdunfield** [comment]
The VAC footer contains two `<nav>` elements that do not have distinguishable labels. I'm not sure whether that's something we should address or not, since updates to this component will be coming from their site and override ours.

**Comment by brdunfield** [comment]
Closed via #1973
