### ISSUE TITLE
Content not included in landmarks

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1757]
From Julianna:

Found with SiteImprove

Content not included in landmarks
1.3.1 Info and Relationships
HTML5 or WAI-ARIA landmarks are used on the page, but not all content is included.

When using HTML5 or WAI-ARIA landmarks it is best practice to include all content on the page in landmarks. In this way users of assistive technologies can use the landmarks for navigating the page without losing track of content.

Make sure that all content on the page is included in HTML5 or WAI-ARIA landmarks.

*Code:*

```<noscript style="transition: none 0s ease 0s;"><div class="css-1wjadmq"><div class="css-1ri8owv"><div class="copy"><p>Javascript is disabled and you may experience reduced functionality. To see a full list of benefits, click <a href='/all-benefits'>here</a>.</p></div></div></div></noscript>```

*Notes*: I'd like to discuss potential false positive.

**Comment by brdunfield** [comment]
<img width="1387" alt="screen shot 2019-03-08 at 9 37 25 am" src="https://user-images.githubusercontent.com/5032149/54034806-d31f2400-4185-11e9-9451-81d872149aa4.png">
<img width="1396" alt="screen shot 2019-03-08 at 9 37 35 am" src="https://user-images.githubusercontent.com/5032149/54034807-d31f2400-4185-11e9-99df-7cbf9ec30dcb.png">
@thomascraig
