### ISSUE TITLE
Number of saved items in the list or (indicated in red circle) are not read to a screen reader.

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1759]
Number of saved items in the list or (indicated in red circle) are not read to a screen reader.

<img width="474" alt="screen shot 2019-01-25 at 10 44 32 am" src="https://user-images.githubusercontent.com/5498428/51763386-76b5e880-20a0-11e9-9c84-3b33684e393c.png">

**Comment by brdunfield** [comment]
Design has changed - red circle no longer exists
