### ISSUE TITLE
Capitalize the names of the checkbox labels that are part of the eligibility-path input.

### ISSUE THREAD

**Issue by leonL** [veteransaffairscanada/vac-benefits-directory#176]
<img width="292" alt="screen shot 2018-05-23 at 11 44 25 am" src="https://user-images.githubusercontent.com/538238/40435730-4efeb972-5e7f-11e8-8e7f-407ecde51f31.png">

**Comment by sastels** [comment]
As mentioned IRL right now we don't have the checkbox value labels translated. I'm in the middle of doing that, which will also fix this issue.
