### ISSUE TITLE
Search box turns yellow when keyword is inputted

### ISSUE THREAD

**Issue by michellengaiCDS** [veteransaffairscanada/vac-benefits-directory#1763]
When I searched a word, the text box background turned yellow.

**Comment by SupeDeDupe** [comment]
Pretty sure it's Google Chrome's autofill causing this. 
https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

**Comment by smcmurtry** [comment]
Maybe if we remove the white space between the x and the magnifying glass that will improve the look:
<img width="890" alt="screen shot 2019-01-29 at 3 13 11 pm" src="https://user-images.githubusercontent.com/5498428/51937415-93238f00-23d8-11e9-9200-c41799c39393.png">

**Comment by michellengaiCDS** [comment]
oh you're right, it is when I use the Chrome autofill.... so there's no way to remove the yellow background colour?

**Comment by SupeDeDupe** [comment]
@michellengaiCDS it's probably possible, but I guess the question is would it be worth it, as that's what Chrome does with autofill on all sites. Removing the very small margin between the x and magnifying glass would certainly be simple and clean it up.
