### ISSUE TITLE
Add FR diagram to doc 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1769]
We use this diagram in [the doc](https://github.com/veteransaffairscanada/vac-benefits-directory/tree/master/doc#how-is-this-different-from-the-testing-workflow) and need to translate it and add it to the French section: 

![img](https://user-images.githubusercontent.com/867334/44407480-31f3b780-a52c-11e8-97d7-6cf8ad046019.png)

Translations: 
Développeur
Créer une demande de tirage
Fusionner la branche maître 
Application d’examen Heroku 
CircleCI – poursuit les tests d’intégration 
Service conteneur d’Azure

**Comment by smcmurtry** [comment]
@maxneuvians Was it you who made this diagram? What program did you use?

**Comment by maxneuvians** [comment]
I did indeed - I used https://www.draw.io/. Simpler solution be to replace the text with the french equivalents with some like the preview app in os x
