### ISSUE TITLE
Data validation url validation error

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#1792]
Data validation page complains about link https://caregiverzone.ca/ even though the link works. Possibly some forwarding is going on that we usually classify as an error (I think an incorrect link to a VAC site forwards to the VAC index page)

**Comment by smcmurtry** [comment]
Yeah I think the error is because that url redirects to: https://caregiverzone.ca/#!/forefront/home

**Comment by sastels** [comment]
I guess we could just check if we're being redirected to the VAC home page. Seems hacky though.

**Comment by brdunfield** [comment]
Related: #1991

**Comment by smcmurtry** [comment]
Closing since I think this is useful behaviour to keep. Failing on links that redirect recently helped us catch a major re-organization of veterans.gc.ca benefits urls.
