### ISSUE TITLE
Create a long text input box component (groundwork for feedback page)

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1794]
Could be based on this govuk component: https://github.com/govuk-react/govuk-react/blob/master/components/text-area/src/index.js

![screen shot 2019-02-04 at 3 46 54 pm](https://user-images.githubusercontent.com/17673146/52236175-20148f80-2894-11e9-8f8b-c5ed8db432d2.png)

Design: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3e0c5acd24f8525cbde78c

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide feedback on the tool](https://trello.com/c/AHCOa5Nw/104-users-can-provide-feedback-on-the-tool)
