### ISSUE TITLE
Non-distinguishable landmarks

### ISSUE THREAD

**Issue by JuliannaR** [veteransaffairscanada/vac-benefits-directory#1809]
**1.3.1 Info and Relationships**
The page contains two or more HTML5 or WAI-ARIA landmarks of the same type that has not been named. Users might not know the difference if it's not somehow explained.

Use the WAI-ARIA attributes 'aria-label' or 'aria-labelledby' to create unique names that describe the purpose of each landmark.

**Code:**

<div class="css-493ori" role="navigation" style="z-index: 2147483646; position: relative;"><div class="css-17fkb1j" style=""><div class="css-n2eig4" style=""><h2 class="css-3hu8g5" style="">Did you find the information you're looking for?</h2><button class="css-m1tm8z" id="feedbackYes" style="">Yes</button>&nbsp; &nbsp;<button class="css-m1tm8z" id="feedbackNo" style="">No</button></div></div></div>

**How do I meet this criteria?**
ARIA13 Using aria-labelledby to name regions and landmarks

<img width="1436" alt="screen shot 2019-02-05 at 8 04 44 pm" src="https://user-images.githubusercontent.com/35537308/52314582-54b24500-2981-11e9-969e-a130891d59d4.png">

**Comment by brdunfield** [comment]
Closed via #1973
