### ISSUE TITLE
Add a dropdown component to the feedback page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1828]
Designs:
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3e0c5acd24f8525cbde78c
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5b2b3ca25e8f427f04bedc

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide feedback on the tool](https://trello.com/c/AHCOa5Nw/104-users-can-provide-feedback-on-the-tool)
