### ISSUE TITLE
Data validation page

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#184]
- [x] Add a page that validates the data
- [ ] all benefits appear in an eligibility path
- [ ] all benefits appear in a need (maybe?)
- [ ]  move the "refresh data" button here
- [ ] check if all the VAC links work
- [ ] make sure important fields aren't empty

**Comment by sastels** [comment]
Note that a first stab at this would just be a page that does one of the above.

**Comment by sastels** [comment]
Have a page that checks that the tables are non-empty. Can add items to it as suggested above as time permits.

**Comment by sastels** [comment]
Note that checking the links will have to be done by the server, NOT the client. Trying to connect to the links in the browser throws a "Cross-Origin Request Blocked" error. 

One idea is to have the server check the links when it loads from AirTable and inject the results into the props for the page.

**Comment by maxneuvians** [comment]
Alternative would be to have a check end point on the server that checks a URL async, that way you would not have a huge load time for the page

**Comment by sastels** [comment]
This issue has been split into separate issues. #399 #400 #401 #402 #403 #404
