### ISSUE TITLE
Receive a "thank you for your feedback" when I hit cancel button on footer feedback

### ISSUE THREAD

**Issue by GBGRAVES** [veteransaffairscanada/vac-benefits-directory#1844]
Clicked on the footer feedback sections and each time I hit the cancel button I received a "thanks for your feedback"

**Comment by courtneycl** [comment]
Expected that the footer would revert back to its initial state.

**Comment by courtneycl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide feedback on the tool](https://trello.com/c/AHCOa5Nw/104-users-can-provide-feedback-on-the-tool)
