### ISSUE TITLE
Can only submit one piece of footer feedback per screen

### ISSUE THREAD

**Issue by GBGRAVES** [veteransaffairscanada/vac-benefits-directory#1845]
Once I submit feedback on either the "Did you find what you are looking for" or "Did something go wrong" it says thank you for submitting feedback and I can enter anything else from the footer unless I move to next screen in the tool.

**Comment by courtneycl** [comment]
@michellengaicds what do you think should happen here from a design perspective?

**Comment by courtneycl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide feedback on the tool](https://trello.com/c/AHCOa5Nw/104-users-can-provide-feedback-on-the-tool)

**Comment by michellengaiCDS** [comment]
Let's add a link after the thank you. So it becomes "Thank you for your feedback. If you have more, let us know." "Let us know" is linked and resets the feedback bar to the default state.
