### ISSUE TITLE
Family member next steps include language for Veteran

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1857]
Selections are as follows: 
Who will be receiving the benefits: Benefits for family members
Service type: Canadian Armed Forces
Status: Still-serving
Is there a service-related health issue? Yes

Next steps includes the following, which is language directed to the Veteran: 
We will obtain a copy of your service health records after we receive your application for disability benefits, which should contain sufficient evidence that your disability is related to your service.

Expected that either that step wouldn't appear, or the language would reflect the path ("We will obtain a copy of the service member's health records after we receive [who's?] application for disability benefits....") 

@michellengaicds @scottlester1

**Comment by courtneycl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users see next steps relevant for their profile and categories](https://trello.com/c/5G0lWiU7/142-users-see-next-steps-relevant-for-their-profile-and-categories)

**Comment by michellengaiCDS** [comment]
Good point. @scottlester1 what do you think of this to be more generic:

We will obtain service health records after we receive an application for disability benefits, which should contain sufficient evidence that the disability is related to service.

**Comment by scottlester1** [comment]
Hmmm. Good question. I just went through the tool and only three benefits showing up are the Veteran Family Program, Pastoral outreach and Vocational assistance....but as soon as they select "released", 9 more benefits appear. I think that next step assumes they are here for disability benefits, when they could just be looking for support during their transition to life after service (through the family program or whatever). That being said, perhaps we should remove it?

**Comment by courtneycl** [comment]
thanks - fixed, closing.
