### ISSUE TITLE
Missing links on VAC office and Transition Centre 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1858]
On the feedback page: https://benefits-prestations.veterans.gc.ca/feedback?lng=en

VAC office should link to: 
EN https://www.veterans.gc.ca/eng/contact
FR https://www.veterans.gc.ca/fra/contactez

Transition centre should link to: 
EN https://www.veterans.gc.ca/eng/services/information-for/caf/ipsc
FR https://www.veterans.gc.ca/fra/services/information-for/caf/ipsc

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can provide feedback on the tool](https://trello.com/c/AHCOa5Nw/104-users-can-provide-feedback-on-the-tool)
