### ISSUE TITLE
Fix margin/padding of radio button group on feedback page

### ISSUE THREAD

**Issue by SupeDeDupe** [veteransaffairscanada/vac-benefits-directory#1867]
Current:
<img width="598" alt="screen shot 2019-02-20 at 3 14 13 pm" src="https://user-images.githubusercontent.com/17673146/53118313-315fcc00-3523-11e9-8594-0e24aff34b0a.png">

Design:
<img width="567" alt="screen shot 2019-02-20 at 3 21 48 pm" src="https://user-images.githubusercontent.com/17673146/53118343-4177ab80-3523-11e9-8a5d-2290982d3cae.png">

**Comment by brdunfield** [comment]
I don't think the circle sizes should be different on this page, but the font / spacing / padding should definitely be fixed.
