### ISSUE TITLE
Link 'case manager' in OSI alert to program page 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1893]
![image](https://user-images.githubusercontent.com/3474250/53262468-a1499000-36a4-11e9-9194-4e708ee68e01.png)

`case manager` should link to: https://www.veterans.gc.ca/eng/health-support/case-management

and in French: 
`gestionnaire de cas` should link to: https://www.veterans.gc.ca/fra/health-support/case-management

**Comment by SupeDeDupe** [comment]
Same problem for 'Disability benefits' link in Educational assistance for children:
<img width="735" alt="screen shot 2019-02-26 at 9 15 22 am" src="https://user-images.githubusercontent.com/17673146/53416054-07862980-39a9-11e9-8dac-19171b301bd1.png">

The links are only implemented in the alert if the benefit requires a gateway benefit. Both the Educational assistance for children and OSI alerts are coming from noteEn + noteFr columns in the benefits sheet in Airtable. There's no code that would currently support changing any of the text from the note columns into links.

**Comment by SupeDeDupe** [comment]
@sidewalkballet for 'Disability benefits' link in Educational assistance for children, would the french link be on `prestations d’invalidité`?

**Comment by courtneycl** [comment]
@SupeDeDupe yep!
