### ISSUE TITLE
mobile: change "saved to your list" to "saved" 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1907]
On mobile the cards have `Save` instead of `Save to your list`: 
![image](https://user-images.githubusercontent.com/3474250/53364310-8da06280-390c-11e9-8a0f-a0ee9f92e661.png)

When you hit save, the text then changes to `Saved to your list`: 
![image](https://user-images.githubusercontent.com/3474250/53364353-9d1fab80-390c-11e9-8905-256a7a5a2080.png)

For consistency and spacing it should just be `Saved`.

**Comment by SupeDeDupe** [comment]
The positioning of the buttons needs to be updated so save button is underneath learn more. The new design has mobile using "Save to your list" and "Saved to your list."

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5c6c0921ae342cd28bcdf2

<img width="368" alt="screen shot 2019-02-26 at 9 33 50 am" src="https://user-images.githubusercontent.com/17673146/53416344-b32f7980-39a9-11e9-8c3b-5ff37eec7596.png">

**Comment by courtneycl** [comment]
great thank you - closing in favour of https://github.com/veteransaffairscanada/vac-benefits-directory/issues/1917
