### ISSUE TITLE
Update mobile card design 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1917]
see: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5c6c0921ae342cd28bcdf2

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by PeterBarrett2** [comment]
Being worked on in Sprint 11

**Comment by smcmurtry** [comment]
@PeterBarrett2 you can see what issues are in sprint 11 here: https://github.com/veteransaffairscanada/vac-benefits-directory/projects/30
