### ISSUE TITLE
cards are all auto-expanded when hitting directory on IE 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1920]
IE only 
1. go through the guided experience, hit view results
2. observe that all the cards have all the sections expanded, and you cannot collapse them. expected the cards would all have collapsed sections that you could expand on click. 

![image](https://user-images.githubusercontent.com/3474250/53438236-770e1000-39cd-11e9-9597-509c86a7aba3.png)

**Comment by smcmurtry** [comment]
Looks like the details element isn't supported in IE. Here's an example of a work-around that I haven't figured out yet: https://github.com/alphagov/govuk-frontend/blob/master/src/components/details/_details.scss

**Comment by smcmurtry** [comment]
Hmm, it looks like the fix is a javascript one: https://github.com/alphagov/govuk-frontend/blob/master/src/components/details/details.js

**Comment by courtneycl** [comment]
verified fixed with https://github.com/veteransaffairscanada/vac-benefits-directory/pull/1926
