### ISSUE TITLE
Things to add for Friday

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#194]
- [x] Patron type first
- [x] Spell out War Service Veteran
- [x] ~Need AirTable snapshot for working group~
- [x] ~use this snapshot in code~
- [x] dropdown for filters rather than checkboxes default “None Selected”
- [x] Gray out filters that aren’t need for a given choice of previous options? Or show one question at a time (show status if CAF, show Vital status only if family)
- [ ] Change show all benefits to clear selections
- [x] Add a counter of # benefits
- [x] Make one columns of benefits
- [x] Put checkboxes in needs dropdown
- [x] Add box to child card and indent more
- [x] Remove “”these benefits” from above child cards
- [x] Make “View Detail” buttons more obvious
- [x] Look into why “With this benefit, you may…,” overflows cards sometimes
- [x] translate View Details on child cards
- [x] Change “Benefit Description” on French page
- [ ] Accessibility: checkbox tables, disabled sections

**Comment by sastels** [comment]
I'll do a PR with
Patron type first 
Spell out War Service Veteran

**Comment by sastels** [comment]
I'll change the checkbox filters to dropdowns

**Comment by smcmurtry** [comment]
I'll add the counter for number of benefits

**Comment by sastels** [comment]
- [x] stop filtering by independent benefits
- [x] don't filter child benefits, just the main cards

(I'll do these)

**Comment by sastels** [comment]
- [x] point all-benefits to Dan
- [x] change language in "Has the service member passed away" filter

**Comment by sastels** [comment]
Good job team! The remaining items will get done as time permits.
