### ISSUE TITLE
Make breakpoints in the app more consistent with the VAC site

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1944]
Currently we're using the default breakpoints that come with the material ui `Grid` component. Is this something we can change? Currently our breakpoints don't match up with the VAC site, which means our layout doesn't match theirs at certain screen widths.

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by brdunfield** [comment]
Looks like these can be customized:
https://material-ui.com/layout/breakpoints/

**Comment by PeterBarrett2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility issues](https://trello.com/c/knKtuM4T/100-accessibility-issues)
