### ISSUE TITLE
Make our max content width and margins consistent with the VAC site

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1945]

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement UI changes to match new VAC site](https://trello.com/c/WzhdqieD/196-implement-ui-changes-to-match-new-vac-site)

**Comment by PeterBarrett2** [comment]
Being worked on in Sprint 11
