### ISSUE TITLE
Update the top banner to include a link to canada.ca

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1959]
<img width="1333" alt="screen shot 2019-03-06 at 4 37 08 pm" src="https://user-images.githubusercontent.com/5498428/53915911-dfdd3400-402e-11e9-8e15-845165737c86.png">

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement a header and footer based on the new VAC header and footer](https://trello.com/c/SP5TarKS/176-implement-a-header-and-footer-based-on-the-new-vac-header-and-footer)

**Comment by courtneycl** [comment]
there are other little differences between the two headers: padding on the left and right, size of the flag and VAC/ACC title.
