### ISSUE TITLE
Close up the space between "Did you find the information you’re looking for?" And the Yes and No options

### ISSUE THREAD

**Issue by michellengaiCDS** [veteransaffairscanada/vac-benefits-directory#1969]
Right now the Yes and No are floating a bit too much to the right :) We can close that up, maybe half that space so it looks more connected to the Did you find the information you're looking for? question.

**Comment by SupeDeDupe** [comment]
This is very tricky because of how the Grid sizing works with Material UI. The Grids are sized in fractions of 12 across the page and they don't pay attention to the content length inside of them when sizing.
