### ISSUE TITLE
Change highlight/focus yellow colour

### ISSUE THREAD

**Issue by michellengaiCDS** [veteransaffairscanada/vac-benefits-directory#1970]
I believe the yellow highlight/focus colour we are currently using on the product is the same yellow that's been carried over from the GDS design system? Let's use a colour more appropriate for the VAC brand. @phil to provide the colour.

**Comment by PhilSmith-VAC** [comment]
If we're after consistency with the VAC site then there shouldn't be any yellow highlight color, only the highlight color of the buttons themselves or the fill for radials and checks for check boxes.

**Comment by PhilSmith-VAC** [comment]
That said, if we must have a highlight color we could use hex fbadld it's within the secondary color palette.

**Comment by smcmurtry** [comment]
The VAC site does have a focus outline, it is just the default blue outline:
<img width="501" alt="screen shot 2019-03-08 at 2 04 45 pm" src="https://user-images.githubusercontent.com/5498428/54049675-28216100-41ab-11e9-8b4c-c7772d3a06de.png">

We could switch to that.

**Comment by PhilSmith-VAC** [comment]
Weird, I wonder why I don't see anything?

Anyhow, I'd do whatever the VAC site is doing.

**Comment by SupeDeDupe** [comment]
The VAC site uses 719EF1 as the highlight colour.
