### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1980]
- [x] Update airtable base links in doc/en/AIRTABLE.md
- [x] Update "Changing the eligibility criteria for a benefit" to reflect the new process
- [x] Remove link to CDS heroku from the doc

**Comment by courtneycl** [comment]
Whatever you change can you please send to translation?

**Comment by smcmurtry** [comment]
I was able to make the changes just by replacing links and deleting text.
