### ISSUE TITLE
Change text in right panel of quick links on favourites page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#1993]
From Michelle: the text should be something like: "The benefits and services you save to this list will remain available only on this device for you to view again."

Currently it is "Remember to read the eligibility criteria for each benefit before applying."

**Comment by courtneycl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users have more content on how Saved list works](https://trello.com/c/Ax1DGhig/190-users-have-more-content-on-how-saved-list-works)

**Comment by SupeDeDupe** [comment]
Closed by #2019
