### ISSUE TITLE
Feedback confirmation page is missing 

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#1999]
1. Be on the feedback page: https://benefits-prestations.veterans.gc.ca/feedback
2. fill out the form, hit `Send`
3. observe the page briefly changes to `/feedback_submitted`, then reloads to an empty feedback page. 

Expected we'd be directed to the feedback confirmation page: 
https://benefits-prestations.veterans.gc.ca/feedback_submitted
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5b2b6a91c96d430b24369d

Note the feedback is captured in Airtable as expected.

**Comment by SupeDeDupe** [comment]
Closed by #2019
