### ISSUE TITLE
Clicking "home" breadcrumb should go to veterans.gc.ca/lng

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#2010]
Currently it goes to the 1st page in the GE. This isn't consistent with the way breadcrumbs work on veterans.gc.ca.

**Comment by brdunfield** [comment]
Will there be a breadcrumb entry to get back to the initial GE page?

**Comment by smcmurtry** [comment]
Yeah, maybe the breadcrumb path to 1st page of GE is: "Home > Find benefits and services"

And the path for the benefits directory is "Home > Find benefits and services > Results"

**Comment by PhilSmith-VAC** [comment]
> Yeah, maybe the breadcrumb path to 1st page of GE is: "Home > Find benefits and services"
> 
> And the path for the benefits directory is "Home > Find benefits and services > Results"

We were just talking about this earlier, I think having a results breadcrumb is definitely the way to go.
