### ISSUE TITLE
There are 2 <nav> elements in the footer that don't have unique aria-labels

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#2031]
Landmarks must have a unique role or role/label combination (`aria-label` OR `aria-labelledby`)

* Tags: unique-landmark
* Issue: Landmarks must have a unique role or role/label combination (`aria-label` OR `aria-labelledby`) (unique-landmark: /insights.html#/content/rules/uniqueLandmark)
* Snippet:  `<nav class="col-x-12 wb-navcurr">`

**Comment by brdunfield** [comment]
This was flagged in #1973 , @thomascraig had mentioned he was going to flag this to VAC comms to resolve.
