### ISSUE TITLE
Update Print & Share icon color

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2041]
Color for the print and share icons should be hex #2F3437FF

https://zpl.io/bAqozwB

![ShareIcons](https://user-images.githubusercontent.com/48225458/55800099-48458800-5aa9-11e9-8340-e93174aa37c2.PNG)

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by apmcguigan** [comment]
https://github.com/veteransaffairscanada/vac-benefits-directory/tree/Print-Share-Alert-Color

Just need proper color values

**Comment by PhilSmith-VAC** [comment]
> https://github.com/veteransaffairscanada/vac-benefits-directory/tree/Print-Share-Alert-Color
> 
> Just need proper color values

Hex value is in first comment. Do you need something different?

**Comment by SupeDeDupe** [comment]
@PhilSmith-VAC don't worry about that comment - he was just letting me know that the locations of those colours have been found in the code and I just need to update the hex colour to the one you specified. I'm going to be refactoring how colours are handled in the backend at some point, so I don't want to be adding in any new colours at this time. This one seems to already exist in the code now, so I'll update the icon colours now.
