### ISSUE TITLE
Alert icon needs to be updated

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2043]
The exclamation icon in the card alerts needs to be resized to 30px x30px and the color changed to hex #2F3437FF.

https://zpl.io/bAqozwB

![AlertIcon](https://user-images.githubusercontent.com/48225458/55799551-0a942f80-5aa8-11e9-8b32-0253e4fdbaa6.PNG)

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by apmcguigan** [comment]
https://github.com/veteransaffairscanada/vac-benefits-directory/tree/Print-Share-Alert-Color

Just need proper color values

**Comment by PhilSmith-VAC** [comment]
> https://github.com/veteransaffairscanada/vac-benefits-directory/tree/Print-Share-Alert-Color
> 
> Just need proper color values

Hex value is in the first comment. You can also find it in Zeplin by clicking on it in one of the mock ups.

**Comment by SupeDeDupe** [comment]
Closes by #2095 (develop) and #2097 into master
