### ISSUE TITLE
Buttons need to be updated.

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2044]
Buttons should be 64px tall with 22px text.

When screen size is compressed the Learn More button text spans 2 lines and there's way more space between the lines than required. I'd prefer to see the text on one line if possible but, if not, the gap between the lines of text needs to be reduced. **NOTE:** _this same line spacing issue occurs with the Save to list link text_

![CardandSideBar](https://user-images.githubusercontent.com/48225458/55798759-24347780-5aa6-11e9-9ed3-8d763cd35753.PNG)

Secondary button color should now be the light grey color #D5E2E9FF

https://zpl.io/VqE4z66

![ContactUs_Proper](https://user-images.githubusercontent.com/48225458/55799341-817cf880-5aa7-11e9-84d9-797f2d1d796a.PNG)

Contact Us button when there’s no results should be the secondary light grey button color #D5E2E9FF not blue.

![ContactUs](https://user-images.githubusercontent.com/48225458/55799211-2d721400-5aa7-11e9-9b9b-1b5f0a964d15.PNG)

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by SupeDeDupe** [comment]
The saved list button issue is replicated in issue #1953, so that one will remain open but may no longer be relevant, because the saved list button has been removed from the benefit cards.
