### ISSUE TITLE
Save and Saved to your list icons

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2046]
These icons should be updated to the ones that are in Zeplin.

https://zpl.io/bAqozwB

![SaveToYourListIcons](https://user-images.githubusercontent.com/48225458/55798311-04e91a80-5aa5-11e9-882e-1aa91b04e1c3.PNG)

**Comment by GBGRAVES** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by SupeDeDupe** [comment]
Closed by removal of saved list in #2087
