### ISSUE TITLE
Update Beta tag base and text

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2047]
Beta tag should have a solid light grey base and pushed up so it takes up less room - base should be 54px tall and the Beta tag 30px tall.

Beta message text should be using the Montserrat regular font @ 14px

https://zpl.io/bAqozwB

**Comment by GBGRAVES** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)
