### ISSUE TITLE
Quick links title needs formatting.

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2048]
The Quick Links title should be 10px with letter spacing of 1.2

https://zpl.io/bAqozwB

![InkedQuickLinks_LI](https://user-images.githubusercontent.com/48225458/55734328-baf52b80-59f5-11e9-8961-2a98c9653210.jpg)

**Comment by GBGRAVES** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)
