### ISSUE TITLE
First GE text sizes need to be updated

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2049]
Text for the message in the grey box on the first GE question should be 24px, not 20px

Sub-heading for first GE question should be 28px, not 36px

https://zpl.io/VDnO7jJ

**Comment by GBGRAVES** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)
