### ISSUE TITLE
Sidebar text formatting

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2050]
Right now, when text in the sidebar options spans two lines, like when the screen is compressed, the first line of the text is centered vertically on the radial or check box it's associated with, then flows down. The text should be considered as a whole so that if there's two lines, the vertical center point between the two lines should line up with the vertical center of the radial or check box it's associated with.

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by SupeDeDupe** [comment]
This issue broadly applies to the radio buttons and check boxes. The same problem happens in Guided Experience.

**Comment by SupeDeDupe** [comment]
Closed by #2183 when removing the the sidebar.
