### ISSUE TITLE
Add a My VAC Account button in Next Steps

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2051]
Under Next Steps we should have a My VAC Account step that has a text link to register and a green My VAC Account button. Refer to Zeplin for design.

Zeplin: https://zpl.io/bAqozwB

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by SupeDeDupe** [comment]
This issue is irrelevant right now because the content does not currently exist. The issue will remain open until we move forward with iterating on the next steps content, as this design may become relevant then.

**Comment by SupeDeDupe** [comment]
Closed in #2183 when Next Steps feature was removed. Should have been done in a separate PR from removing the sidebar, but it wasn't.
