### ISSUE TITLE
Breadcrumb spacing issue

### ISSUE THREAD

**Issue by PhilSmith-VAC** [veteransaffairscanada/vac-benefits-directory#2052]
There should be more space between the text and the > of the breadcrumbs ~ 10px

Zeplin: https://zpl.io/bAqozwB

**Comment by PhilSmith-VAC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design review](https://trello.com/c/HRB4XCpl/177-design-review)

**Comment by SupeDeDupe** [comment]
The breadcrumbs are also colour 434458, according to design.
