### ISSUE TITLE
Navigation / Selection / Saved List issues

### ISSUE THREAD

**Issue by PeterBarrett2** [veteransaffairscanada/vac-benefits-directory#2060]
Found during first pass end-to-end testing, several issues related to the users selections and the tool, that I think are tied to how we're using the Saved List feature. The Saved List feature has some issues surrounding privacy that will likely make some users very paranoid, so we might have to revisit how we're using it.

**1. User   can make a selection on the first question, and it will be rememberd if they   click on the 'Back' button in   the tool.**
1. Load   up the FBS tool     
2. In the first question 'Select who would be receiving   the benefits.', select 'Benefits   for family members'     
3. Click on the 'Next'   button     
4. Instead of responding to the next question, click on the 'Back' button in your browser toolbar (not the tool).
**Expected Result:** User is taken back to the first question 'Select who would be receiving the benefits.' and see's that the selection they had made, 'Benefits for family members' is selected.
**Actual Result:** User sees the page with nothing selected.

**2. User can hard refresh the page and start the tool fresh with no previously entered selections remembered.**
1. Load up the FBS tool 
2. In the first question 'Select who would be receiving the benefits.', select 'Benefits for family members' 
3. Click on the 'Next' button     
4. Instead of responding to the next question, click on the 'Back' button below the question.     
5. On your keyboard, do a hard refresh by pressing CTRL+R
**Expected Result:** User should see the page refresh, and then see the tool completely blank with no selections made.
**Actual Result:** User see's the first question with their selection remembered.

The next two are semi-related, and produce the same result, where the Saved List persists when it should not.

**3. Users can NOT see their saved list if they use the tool in an incognito browser tab.**
1.   Load up the FBS tool
2. On the landing page, click on the 'Skip question' link     
3. On the 'Select the categories of benefits you   want to see.' screen, click on the 'Skip question' link     
4. On the results page, scroll through the list and find the 'Veterans emergency fund' card     
5. Click on the 'Save to your list' text link in the bottom right corner of the card     
6. On the results page, scroll through the list and find the 'Career transition services' card     
7. Click on the 'Save to your list' text link in the bottom right corner of the card     
8. On the results page, scroll through the list and find the 'Clothing allowance' card     
9. Click on the 'Save to your list' text link in the bottom right corner of the card     
10. Click on the 'Saved list (3)' text link that is pinned to the top of the window     
11. After confirming those three programs are in your list, close the   browser tab, or the browser entirely     
12. Open up a new incognito/private browser window or tab     
13. Load up the FBS tool     
14. On the landing page, click on the 'Skip   question' link     
15. On the 'Select the categories of benefits   you want to see.' screen, click on the 'Skip question' link     
16. Click on the 'Saved list' link
**Expected Result:** User should see nothing.
**Actual Result:** User can still see their previously saved list.

**4. Users can NOT see their saved list if they clear their browser cache and cookies.**
1. Repeat steps 1-11 from the previous test
12. Go to your browser settings and clear you cache, including cookies.
13. Load up the FBS tool
14. On the landing page, click on the 'Skip question' link
15. On the 'Select the categories of benefits you want to see.' screen, click on the 'Skip question' link
16. Click on the 'Saved list' link
**Expected Result:** User should see nothing.
**Actual Result:** User can still see their previously saved list.

This one is related to both navigation and the Saved List, the actual test I was doing passed, but I noticed this while doing it.
**5. I encountered and can reproduce a scenario, where a user would be on the results screen, click on 'Save to your list' and then click on 'Learn More', and then from the program page, if they click back on their browser, the card is not saved.**

A simple solution for the above issue, that might also alleviate some of the breadcrumb/navigation issues, would be to have all the Learn More buttons open in a new tab, instead of taking the user out of the tool.

**Comment by SupeDeDupe** [comment]
Closed in favour of #2084.
