### ISSUE TITLE
Missing count of saved issues in Saved Lists in French

### ISSUE THREAD

**Issue by cecaiss** [veteransaffairscanada/vac-benefits-directory#2061]
When there is only one saved item on the list, in French the 1 is missing.

![image](https://user-images.githubusercontent.com/47643987/55429157-2c9a2900-5561-11e9-96e7-ea204b9c59c2.png)

**Comment by cecaiss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs needing to be fixed for Beta live](https://trello.com/c/05FYPQew/186-bugs-needing-to-be-fixed-for-beta-live)

**Comment by SupeDeDupe** [comment]
Closed in favour of #2084.
