### ISSUE TITLE
Refine child benefit card

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#208]
Update UI of child card to bring it in line with ( https://projects.invisionapp.com/freehand/document/aqX9F1ne1). look at things like: change the "View Details" button to a "Find out more" link AND  add "Available to" data (to AirTable and app) AND use your judgement or we will replace you with a machine learning algorithim

**Comment by smcmurtry** [comment]
"Available to" data still needs to be added to AirTable and app. The other stuff is done.
