### ISSUE TITLE
After submitting feedback, user is taken to directory page 

### ISSUE THREAD

**Issue by GBGRAVES** [veteransaffairscanada/vac-benefits-directory#2117]
The link presented to user after submitting feedback is https://benefits-avantages.veterans.gc.ca/benefits-directory? - even though I started on the GE page 1 

Is the assumption that the user would be submitting feedback after going through the tool anyway?

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feedback submitted may need some design work](https://trello.com/c/yqKgM3un/210-feedback-submitted-may-need-some-design-work)
