### ISSUE TITLE
Icons need adjusted to render correctly in IE

### ISSUE THREAD

**Issue by thomascraig** [veteransaffairscanada/vac-benefits-directory#2124]
![image](https://user-images.githubusercontent.com/1898328/56920304-3f891600-6a99-11e9-9063-204cbd818640.png)

CSS related position issue.

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cleanup fallback page for IE10](https://trello.com/c/nuLnNpHW/207-cleanup-fallback-page-for-ie10)
