### ISSUE TITLE
Investigate search feature

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#264]
maybe: https://lunrjs.com/

**Comment by maxneuvians** [comment]
State of research: Lunr seems to be the best solution. The question is how we want the filtering to work. Currently the profile filters and needs create a set of benefits. Then a search is applied on that set. If the search is empty or blank, the whole set is returned, if the search is not empty then the set is limited to matches contained in the title or description. There is some weirdness about how we we will treat child benefits.  For example, we will need to show parents even if the match only applies to children. We then also will pass the search string to benefit cards and we will need to highlight the string in the text.

**Comment by sastels** [comment]
Search is still pre-alpha but I think we have a good sense of what Lunr can do and how to use it. 💯
