### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#276]
Ability to print what they have selected (filters & needs) and the filtered benefits. Instructions included (ex. 1800 number)

https://github.com/gregnb/react-to-print

**Comment by smcmurtry** [comment]
My idea is for this to work the same way as printing an email thread in gmail:
1. You click the print button
2. A new tab opens with the content re-formatted for printing
3. The browser's print modal window opens automatically

**Comment by smcmurtry** [comment]
@sastels @maxneuvians I want the print view to be a new page, but I don't know how to get data (like filteredBenefits) to the new page. Should I try to save the data with Redux in A.js and then load it in print.js?

**Comment by sastels** [comment]
that sounds reasonable?

**Comment by maxneuvians** [comment]
You can try that, easier might be just to pass them as part of the URL the same way state is reflected in the URL of A

**Comment by smcmurtry** [comment]
@maxneuvians I like your suggestion - that is probably the simplest solution. I tried the react-to-print package but it seemed buggy - it didn't open the print modal consistently.
