### ISSUE TITLE
Change profile selector to be more reactive

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#286]
- initially just show patron type filter
- when that's answered (if not organization), show service type
- then show service status (don't show deceased if patron type is service person)

**Comment by smcmurtry** [comment]
Based on today's discussion w/ design: not applicable options will be disabled (greyed out), not hidden

**Comment by sastels** [comment]
Though I think the idea is for if nothing is selected then only the top filter group is displayed? In any case, we should start with a PR that just does the greying-out part, then if desired do a PR that hide things initially.

**Comment by smcmurtry** [comment]
- [x] disable not-applicable options
- [x] make filter questions appear one at a time

**Comment by sastels** [comment]
@maxneuvians The idea for the second part is that initially only the Recipient filter is shown, then when the user selects one, the Service Type is shown, then finally the Service Status. Also, if "Organizations" is selected then the other two filters are not shown.
