### ISSUE TITLE
Write tests that make sure the filter clear buttons work

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#303]

**Comment by maxneuvians** [comment]
Seems like it was done in:
https://github.com/cds-snc/vac-benefits-directory/blob/master/__tests__/components/profile_selector_test.js#L151-L159
and
https://github.com/cds-snc/vac-benefits-directory/blob/master/__tests__/components/needs_selector_test.js#L120-L124
