### ISSUE TITLE
Fix Refresh Cache button

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#306]
Doesn't seem to work, at least on Azure.

**Comment by maxneuvians** [comment]
Button is broken, backend functionality still works, try going to `/refresh` as an example

**Comment by sastels** [comment]
👍 yeah, loading `/refresh` works. Just needs some 👀 on the button then.

**Comment by maxneuvians** [comment]
maybe upgrade to next6 put in some new conventions
