### ISSUE TITLE
Add PR link to vac-review

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#334]
link to the actual PR as well as the app

**Comment by maxneuvians** [comment]
Working on this - need to update xCode to get the dev tools for the cloud functions 🙄

**Comment by maxneuvians** [comment]
We can put anything from here we want in those: https://api.github.com/repos/cds-snc/vac-benefits-directory/pulls/337

**Comment by sastels** [comment]
neat!

**Comment by maxneuvians** [comment]
Closed in #338
