### ISSUE TITLE
Skipping GE questions produces some funny results

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#367]
Start GE
Click Next
Click Next
Click Deceased

Nothing is selected on result page.

Should next only be clickable if something was selected?

**Comment by smcmurtry** [comment]
I just chatted with Michelle - she suggests that if you click Next from the first question with nothing selected, it skips to the Needs question

**Comment by maxneuvians** [comment]
Closed in #394
