### ISSUE TITLE
Guided Experience: Selecting veteran + WWII should hide the still-serving option

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#369]
This logic is already implemented in the RadioSelector component. Is it possible to re-use this?

**Comment by sastels** [comment]
probably not  - in the RadioSelector it actually just disables it, doesn't hide it. Also, if you selected Veteran and then WSV then there would only be the "released" option, so probably we would want the app to auto-select "released" and skip to Needs.
