### ISSUE TITLE
Implement the "health issue" profile question

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#370]
https://projects.invisionapp.com/share/EWL00LNSVF2#/screens/303264742

Will require changes to air tables and app. AFAIK we don't have the data for airtables yet.

**Comment by sastels** [comment]
We would have to go through the list of benefits and/or benefit navigator data to figure out the eligibility paths. Adding in the exta filter to A, GE and BB won't be too hard. I doubt if we can get all this done by Wednesday. Probably by the end of the week though, if not much else comes up.

**Comment by smcmurtry** [comment]
We have a need tag for "service-related health issue", so we already have a lot of the data needed to implement this question. I went through the VAC website for the benefits with this tag to determine if they were only available to those with a service-related health issue, or if that is not a hard requirement. Here are the results:

Only eligible if you **or your family member** have a service-related health issue:
- Veteran Family Program
- Group Health Insurance
- Canadian Forces Income Support 
- Supplementary Retirement Benefit
- Clothing Allowance
- Career Impact Allowance Supplement
- Career Impact Allowance
- Exceptional Incapacity Allowance
- Earnings Loss Benefit
- Disability Pension
- Critical Injury Benefit
- Disability Award

Not only eligible if you **or your family member** have a service-related health issue:
- Attendance Allowance
- Detention Benefits
- Funeral and Burial Assistance

**Comment by smcmurtry** [comment]
closed by #567
