### ISSUE TITLE
Fix margin and/or padding on Alpha banner

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#379]
I just took a look at the IRCC project and they have their alpha banner aligned properly: 
<img width="1200" alt="screen shot 2018-06-18 at 10 48 53 am" src="https://user-images.githubusercontent.com/5498428/41543717-695f721e-72e5-11e8-9d0e-fbeab456d484.png">

They created their own component as a wrapper around the gcui component: https://github.com/cds-snc/ircc-rescheduler/blob/master/web/src/components/AlphaBanner.js

Seems like something worth stealing? 😄

**Comment by sastels** [comment]
fixed in #432
