### ISSUE TITLE
Implement Basic Accessibility Patterns (based on IRCC Level Access review)

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#380]
The IRCC group had accessibility testing done. Many of the issues that were discovered apply to our project too. Here are some of them:

- [x] add `alt-text` to all images (for us this is gov't logos)
- [x] set `<html lang="xx">` attribute correctly (right now it doesn't update on language change)
- [x] add a `lang` attribute to the switch language button
- [x] add `htmlFor` attribute to `FormControlLabel` components so that we have`<label for="id">` and `<input type="radio" id="id">` in the DOM
- [x] use `<h1>` and `<h2>` elements for page title and some other headings rather than the material-ui `Typography` components. This helps screen readers know what the headings are.
- [x] set a page-specific `<title>` in `<head>`
- [x] Add `role="img"` to all SVG

**Comment by maxneuvians** [comment]
```
set <html lang="xx"> attribute correctly (right now it doesn't update on language change)
```
I spent some time looking into this and could not get it to work because the html tag is outside of the reactive scope. The best I could get it to do was to load the language of the browser. So if the browser is set to french it should show `lang='fr'`.

**Comment by danprime** [comment]
Add `role="img"`to all SVG  ref: https://css-tricks.com/accessible-svgs/

**Comment by smcmurtry** [comment]
Closed by the sub issues referenced above
