### ISSUE TITLE
Data Validation: check important fields are filled in

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#403]
Make sure that all the text fields are filled in, for example names, descriptions and links in both languages, for all tables.

Note that some fields are allowed to be empty, ie fields that are links to other tables.

**Comment by apmcguigan** [comment]
Should the policy links be included in the data-validation page

**Comment by sastels** [comment]
Right now don't bother with them - we don't use them in the app. We can always add them in later if they become relevant (or delete them from AirTable if not)
