### ISSUE TITLE
Revise footer feedback

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#406]
* remove right footer question (pops up if "No" selected)
* revise yes/no question text (text to be provided by design)

**Comment by maxneuvians** [comment]
~remove right footer question (pops up if "No" selected)~ in #483

**Comment by sastels** [comment]
Style as in
 https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b16f12431e8b89541f8cf09

![image](https://user-images.githubusercontent.com/8228248/43470882-a6126484-94b7-11e8-9288-c9d7c97bc1e3.png)
