### ISSUE TITLE
Create a staging site

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#43]
Some of the tools need a real website to test / use - It would be good if we could have a staging site (Azure or AWS) that we could push a branch / docker container to manually. (ie put something on the web without merging the branch to master).

**Comment by maxneuvians** [comment]
I suggest we create a staging branch and then merge our stuff into that and once it passes staging merge it into master. Circle CI can deploy based on branch.

**Comment by sastels** [comment]
I don't think we should always require a passing merge to staging before merging to master - for example, if staging is behind master then it's likely that after merging branch -> staging, staging is identical to branch. So you haven't gained any new confidence (only a false sense of security). One would have to manually pull master into staging beforehand, which one could do to branch.

The exception is changes that are related to deploy / real website which cannot be tested in the branch. Here having a staging site will be really useful.

**Comment by maxneuvians** [comment]
Point taken!

**Comment by maxneuvians** [comment]
Heroku solved the issue
