### ISSUE TITLE
Store filtered benefits in redux rather than props

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#434]

**Comment by maxneuvians** [comment]
Rather than storing a filter set in state, could we derive computed state? https://redux.js.org/recipes/computing-derived-data

**Comment by smcmurtry** [comment]
Great idea. Also here's a library that looks like it will let us mock our redux store for testing: https://github.com/dmitry-zaets/redux-mock-store
