### ISSUE TITLE
Make it obvious that results have changed when a new profile/need is selected

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#437]
This is a request from design based on user feedback. 

Proposed solution is to reload the page and scroll so that "Showing x benefits for you to consider" is at the top of page, whenever a new profile/need is selected in BB.

**Comment by sastels** [comment]
This might be of help:
https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js
