### ISSUE TITLE
Fix Web Application Header

### ISSUE THREAD

**Issue by danprime** [veteransaffairscanada/vac-benefits-directory#449]
From a recent Security Scan from ZAP where they scanned https://cdsvacpoc.azurewebsites.net/A?section=A1&lng=en and scored it an F. 

Here are a *few* issues that might help reduce the score:

- [x] X-Frame-Options Header Not Set
- [x] Incomplete or No Cache-control and Pragma HTTP Header Set
- [x] Web Browser XSS Protection Not Enabled
- [x] X-Content-Type-Options Header Missing

May need to talk to Damien about further security issues.

![_users_dan_downloads_vac_passive html](https://user-images.githubusercontent.com/2610409/41999886-f8ea064e-7a2c-11e8-86ed-d4ffbd553dc5.png)

**Comment by maxneuvians** [comment]
Fixed in #455
