### ISSUE TITLE
Make bilingual urls

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#486]
Right now they’re English.  Need French versions that point to the corresponding page with lng=fr set.

**Comment by maxneuvians** [comment]
https://github.com/fridays/next-routes

Caveat: https://github.com/zeit/next.js/pull/4094

**Comment by sastels** [comment]
We can probably punt this to VAC to deal with, or at least wait until we know how the app is going to sit in the VAC site.
