### ISSUE TITLE
Bookmark button style change

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#545]
Change capitalization, horizontal alignment, text colour, and remove 's'
Current:
<img width="357" alt="screen shot 2018-07-11 at 2 15 20 pm" src="https://user-images.githubusercontent.com/5498428/42591510-e03c5316-8514-11e8-9442-b08d8f34c4ff.png">

Design:
<img width="496" alt="screen shot 2018-07-11 at 2 13 37 pm" src="https://user-images.githubusercontent.com/5498428/42591488-d1242e9e-8514-11e8-830b-09de7c5c605e.png">

**Comment by maxneuvians** [comment]
Closed in #546
