### ISSUE TITLE
Update Directory header layout

### ISSUE THREAD

**Issue by leonL** [veteransaffairscanada/vac-benefits-directory#548]
There is a new layout of the directory header elements. Please update the site to look like:
https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b45ad8f22c744f901194d96

**Comment by maxneuvians** [comment]
Should be completed in https://github.com/cds-snc/vac-benefits-directory/pull/540 or do mean something else?

**Comment by maxneuvians** [comment]
All good!
