### ISSUE TITLE
Guided Experience refactor - Remove progress bar

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#549]

**Comment by maxneuvians** [comment]
<img width="637" alt="screen shot 2018-07-12 at 7 38 14 am" src="https://user-images.githubusercontent.com/867334/42631009-e95f8c6e-85a6-11e8-86b4-579b6a63e954.png">

**Comment by smcmurtry** [comment]
I don't think that's a progress bar, just a fixed length line:
![screen shot 2018-07-12 at 9 41 02 am](https://user-images.githubusercontent.com/5498428/42636907-de0adec0-85b7-11e8-9433-27b84c660f71.png)
