### ISSUE TITLE
Accessibility testing

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#55]
Find out what GoC standards are and test for them.

**Comment by maxneuvians** [comment]
https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd
https://github.com/paypal/AATT

**Comment by leonL** [comment]
Consider both automated and QA testing.
Eva is investigating accessiblity issues related to React as of April 13th dev meeting.
