### ISSUE TITLE
Make the filter questions a bit wider to prevent line break in "show me benefits for:"

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#560]
![screen shot 2018-07-12 at 4 24 17 pm](https://user-images.githubusercontent.com/5498428/42657414-1c7178a8-85f0-11e8-832e-6971bdc9ac70.png)

**Comment by maxneuvians** [comment]
Could also adjust text content or size of text, adding another column might be too much
