### ISSUE TITLE
Make a "device size" property in redux

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#563]
Say something like small, medium, or large. This would allow components to fine tune their styling on mobile

**Comment by maxneuvians** [comment]
CSS already has a thing called `mediaQuery`

https://www.w3schools.com/css/css_rwd_mediaqueries.asp

Material UI uses them:

https://material-ui.com/layout/breakpoints/

And you can use them inside the theme
https://stackoverflow.com/a/50780995
or define your own
https://github.com/cds-snc/vac-benefits-directory/blob/master/pages/index.js#L34

So we might be able to use this for the purposes of this issue?

**Comment by sastels** [comment]
this is interesting. probably good enough for us 👍 (especially if it's standard way of doing these things)

**Comment by maxneuvians** [comment]
👍

**Comment by sastels** [comment]
huh, these methods will work with CSS but not if we want to base javascript code on it. For now I'll add `pageWidth` to redux

**Comment by maxneuvians** [comment]
closed by @sastels in #685
