### ISSUE TITLE
Fix hiding back button

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#582]
To replicate:
- go to GE
- choose an option, press next
- the new screen doesn’t have a visible Next button

![c1eeb6c0-4ba2-49dc-8820-f36cb4b77553](https://user-images.githubusercontent.com/8228248/42789278-68119082-8932-11e8-9661-c2179a3007e6.jpeg)

**Comment by maxneuvians** [comment]
Looks like happens consistently on iOS

**Comment by sastels** [comment]
Don't get the bug on desktop (Chrome / Firefox / Safari). Get it on iPad and iPhone. Don't know about Android

**Comment by sastels** [comment]
So it looks like what's happening is that the phone has a hover that is still over the button that you just clicked (as if you clicked the mouse and left it there). Now that @maxneuvians has darkened up the button "hover" style, the button is visible. It's still slightly lighter than the "normal" button look, but definitely not a blocker in using the app.
