### ISSUE TITLE
Make disclosure header grey when expanded

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#615]
![image](https://user-images.githubusercontent.com/8228248/42893199-ae932e8a-8a81-11e8-8162-8078e17ad6c8.png)

**Comment by sastels** [comment]
or possibly make everything gray?

**Comment by smcmurtry** [comment]
![screen shot 2018-07-19 at 1 36 36 pm](https://user-images.githubusercontent.com/5498428/42960080-cdbb6386-8b58-11e8-80fd-197babe6e8df.png)
