### ISSUE TITLE
funny button padding

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#618]
"View Saved Benefits" button on BD. padded on right but not on left. print button similar.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/8228248/42905111-1241f83a-8aa5-11e8-9732-26409257ebc9.png">

**Comment by maxneuvians** [comment]
It was to pull it over to align with the left margin of the page

**Comment by sastels** [comment]
I think David was more bothered by the fact that the two sides aren’t evenly padded.
