### ISSUE TITLE
Back button on Bookmark page

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#619]
No link back to BD. Do we want one?

**Comment by smcmurtry** [comment]
We now have a design for this!

![screen shot 2018-07-23 at 4 53 58 pm](https://user-images.githubusercontent.com/5498428/43102422-1ed47184-8e99-11e8-8204-9c0fb6907a2e.png)

**Comment by sastels** [comment]
@buckley-w-david there, you happy now?

**Comment by buckley-w-david** [comment]
![](https://media.giphy.com/media/111ebonMs90YLu/200.gif)

**Comment by sastels** [comment]
resolved in #679
