### ISSUE TITLE
fix failing master

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#642]
failing because of docker image changes :( 
Probably need to fix the minor version

**Comment by maxneuvians** [comment]
Is it good enough to specify node engine `10.x` in packages.json? Might be a bit more flexibility

**Comment by smcmurtry** [comment]
Yeah that may be a good idea. When I upgraded my node it went to v10.7 which caused a build error until I set `"node": "10"` in packages.json. Then the build worked so I don't think there was a compatibility issue. I ended up downgrading to v10.6 anyway.

**Comment by sastels** [comment]
huh. let me see if that fixes everything...
