### ISSUE TITLE
Privacy Link in Footer

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#646]
Currently does nothing

**Comment by sastels** [comment]
Should we link to https://digital.canada.ca/legal/privacy/ ?

**Comment by maxneuvians** [comment]
Does VAC have it's own privacy? Should be an airtable link! (Solution to all problems)

**Comment by sastels** [comment]
huh. yeah, we can make it a link in airtable.
This is all I could find for VAC http://www.veterans.gc.ca/eng/copyright#privacy_notice
