### ISSUE TITLE
Add phone number, business hours to the Area office air table

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#668]
Not present in the API, but it is present on the VAC website...

http://www.veterans.gc.ca/eng/contact/map

**Comment by sastels** [comment]
Didn’t @thomascraig say that he knew where a list of offices is (Ie so we don’t have to scrape the web site)?

**Comment by smcmurtry** [comment]
@sastels the API is here: http://www.veterans.gc.ca/xml/jsonp/app.cfc?method=remoteGetServiceBenefitsLocations&callback=?&language=en

**Comment by smcmurtry** [comment]
@thomascraig generated the data we need
