### ISSUE TITLE
Copy Tracker documentation template

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#676]
copy over the Tracker documentation template for us to use.

https://github.com/cds-snc/tracker
https://github.com/cds-snc/track-web
https://cds-snc.github.io/track-web-security-compliance/code-and-repositories/

**Comment by maxneuvians** [comment]
Decided to create the content first and then find the right format.

**Comment by maxneuvians** [comment]
Completed by @leonL https://github.com/cds-snc/vac-benefits-directory-documentation
