### ISSUE TITLE
change repo name to veterans-affairs-canada-benefits-directory

### ISSUE THREAD

**Issue by leonL** [veteransaffairscanada/vac-benefits-directory#71]
Optimize for others from outside of the immediate stakeholders being able to find it. Alpha and Beta releases will be designated by labels. A project starter kit can be forked from the project after the Alpha is released.

**Comment by sastels** [comment]
@leonL @maxneuvians that's a really long name, is that really better than just "VAC-benefits-directory" or "VAC-benefits-at-a-glance"?

**Comment by sastels** [comment]
from talk IRL: VAC-benefits-directory

**Comment by sastels** [comment]
Everything seems to be working with the renamed repo! Had to change CircleCI, Heroku, and Azure to use the new name.
