### ISSUE TITLE
Weird styling while directory is loading.

### ISSUE THREAD

**Issue by danprime** [veteransaffairscanada/vac-benefits-directory#713]
The information is there but it's squished and the loading bar indicates something is loading.

This showed up on Nexus 4 and LG 4.

![screenshot_2018-07-26-12-14-13](https://user-images.githubusercontent.com/2610409/43270395-f734486c-90c2-11e8-9844-46e4cb6a0d4b.png)

I can't replicate this using Network Throttling on Chrome Dev tools.

To check you'll need to use the Nexus 4 or LG 4 (from the CDS Device library - see Hillary).

**Comment by sastels** [comment]
There's also an issue with the search button on the index page popping in and out. I think it's SSR vs the client rendering with a small pageWidth.
