### ISSUE TITLE
Redux data is wiped whenever you visit a new page

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#717]
We haven't noticed this yet because we're always passing data in the url when we go to a new page.

I discovered this while trying to set the closest office in redux from /map, and reading it from redux in /print.

**Comment by maxneuvians** [comment]
I think this is expected - so navigating between URLs does not persist state if it is actually a server fetch. Usually it is done with sessions which are cookies on the front end that have state in the back end. SPA usually do this by rewriting the URL without actually doing a server fetch. This is the difference between linking with `<a href="xxxx"` and doing a `Link` in `next`. @sastels why did we abandon using `Link`s? Did we just now know enough or did we have a good reason?

**Comment by sastels** [comment]
No good reason I believe. Or, at least, I think we got rid of them when we decided that we shouldn’t have different pages, we should just do everything in one (and lo, `A.js` was born)

**Comment by smcmurtry** [comment]
Thanks for the `Link` suggestion! I switched the navigation over to use those and now it's working.

**Comment by maxneuvians** [comment]
Really? Awesome!!

**Comment by maxneuvians** [comment]
I think we actually removed it because of cypress.
