### ISSUE TITLE
change misc links to Link

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#721]
use the Next link as described in
https://github.com/zeit/next.js/#with-link

(@smcmurtry doing links to print, map, favourites)=

- [x] from index page, links to GE and benefits-directory and search button
- [ ] link to privacy page in footer (doesn't seem to load page)
- [ ] GE prev button (couldn't get working)
- [ ] GE next button (couldn't get working)
- [ ] benefit cards:
  - [ ] "learn more"
  - [ ] required parents
  - [ ] children (in embedded benefit card)

Also: should we change the link to phone # on map page?

**Comment by sastels** [comment]
We're having problems with the "Find out more" Button. Wrapping in a Link didn't work. Possibly we have a problem with `Buttons` which go to an off-site href. Wrapping in a `Link` with the corresponding href causes the button to no longer navigate to the new page. 

Mote that if we changed the `Button` to an anchor then the link worked.

**Comment by maxneuvians** [comment]
Might solve #720 if you wrap it in a link and send it back to benefits directory?
