### ISSUE TITLE
Search Stem issues mixing up "home" and "hope"

### ISSUE THREAD

**Issue by danprime** [veteransaffairscanada/vac-benefits-directory#742]
When searching for "hope" the HOPE benefit appears (as expected) but the Veterans Independence Program also shows.

<img width="783" alt="screen shot 2018-07-31 at 3 10 27 pm" src="https://user-images.githubusercontent.com/2610409/43481415-e6058d5c-94d3-11e8-8b87-d3c5fa243dc0.png">

**Comment by sastels** [comment]
I believe this is due to the fact that we're allowing spelling mistakes. We can revisit this if/when we change how our search is working.
