### ISSUE TITLE
Integrate Data Store Into App

### ISSUE THREAD

**Issue by leonL** [veteransaffairscanada/vac-benefits-directory#75]
Are there any related nextjs best practices that should be observed in terms of what we chose, or how it is configured?

**Comment by maxneuvians** [comment]
Based on:
https://github.com/zeit/next.js/issues/2252#issuecomment-308206320

check out:

https://github.com/zeit/next.js/tree/master/examples/with-redux
https://github.com/zeit/next.js/tree/master/examples/with-refnux
https://github.com/zeit/next.js/tree/master/examples/with-mobx
