### ISSUE TITLE
Map page crashes on iphone 5s

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#750]
(and maybe others). Might be the geolocation code - might need to check if related objects exist before using.

**Comment by maxneuvians** [comment]
Does not happen on 7

**Comment by sastels** [comment]
currently working on 5s if you don't allow geolocation. crashes if you allow.

**Comment by maxneuvians** [comment]
From browserstack `'undefined' is not a function (evaluating 'Object.values(officeDistance)')`
