### ISSUE TITLE
Move alpha banner below flag banner and change styling

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#784]
![screen shot 2018-08-02 at 2 56 32 pm](https://user-images.githubusercontent.com/5498428/43646885-155bd976-9704-11e8-9961-ab46193fe87d.png)

**Comment by sastels** [comment]
Can you keep the text in a separate column from the alpha badge? on mobile the email address goes below the badge
<img width="197" alt="image" src="https://user-images.githubusercontent.com/8228248/43653918-8bcf627c-9717-11e8-92c9-70177257b15f.png">

Also, we should probably 🔥 the thin blue bar under the alpha bar.
