### ISSUE TITLE
Map page not working on windows/IE

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#785]

**Comment by thomascraig** [comment]
![ie9-error](https://user-images.githubusercontent.com/1898328/43649597-ed34f77e-9713-11e8-89a9-23658718f030.png)
![ieedge-error](https://user-images.githubusercontent.com/1898328/43649598-ed567548-9713-11e8-897a-288295100a08.png)

Couple IE issues (or likely related) but tested in IE Edge and IE 9

**Comment by sastels** [comment]
Via Browserstack:

Not Working
Windows 10, IE 11
Windows 8.1, IE 11

Working:
Windows 10, Edge 15
Windows 10, Firefox
