### ISSUE TITLE
Move search box

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#788]
![screen shot 2018-08-03 at 11 54 27 am](https://user-images.githubusercontent.com/5498428/43652755-172f80b2-9714-11e8-849d-496d7a4ddc0c.png)

**Comment by sastels** [comment]
So @maxneuvians and I (ok, mainly @maxneuvians ) found the right way to do mobile vs non-mobile differences. We shouldn't use pageWidth as we used to (that causes a flicker when the app loads). Instead we should use breakpoints https://material-ui.com/layout/breakpoints/
If these are used in the css to show / hide components then there isn't a flicker.
See https://github.com/cds-snc/vac-benefits-directory/blob/master/components/search.js#L60 for an example.

**Comment by sastels** [comment]
wait, @smcmurtry is this issue for mobile, or for the desktop version?

**Comment by smcmurtry** [comment]
@sastels Yes sorry this is for both desktop and mobile
