### ISSUE TITLE
Remove ripple animation for buttons on keyboard tab - a11y

### ISSUE THREAD

**Issue by melodyma** [veteransaffairscanada/vac-benefits-directory#796]
Issue: Ripple animation still happening on buttons when someone tabs into them using keyboard.

Steps to reproduce:
1. Go to search results page in desktop viewport size
2. Use keyboard to tab into "Saved Benefits" or "Print this Page"
3. Observe animation that happens, which is a flash of the ripple animation

Expected results:
No ripple animation plus whatever the standard hover and/or focus state is.

**Comment by maxneuvians** [comment]
The spec does not recommend a ripple on focus, but only on click: https://material.io/design/components/buttons.html#text-button (browse down to state) so it makes sense to remove it.
