### ISSUE TITLE
Focus states for Categories do not have sufficient contrast - a11y

### ISSUE THREAD

**Issue by melodyma** [veteransaffairscanada/vac-benefits-directory#797]
Focus and focus/selected states for Categories buttons do not have sufficient colour contrast to meet WCAG. 

Focus state:
![screen shot 2018-08-03 at 9 13 52 pm](https://user-images.githubusercontent.com/6571996/43672444-ddfa1a74-9762-11e8-9f84-33b9d97d58c7.png)

Focus and selected state:
![screen shot 2018-08-03 at 9 14 13 pm](https://user-images.githubusercontent.com/6571996/43672443-d7e3386e-9762-11e8-8f40-00f7a63ac04f.png)

Background on why sufficient colour contrast is necessary: https://www.w3.org/WAI/perspective-videos/contrast/
Solution: https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#contrast-minimum

**Comment by maxneuvians** [comment]
Looks like these are being replaced in the next iteration - which should solve the issue. Thank you for reporting these though @melodyma, it is really helpful,

<img width="282" alt="screen shot 2018-08-07 at 7 52 59 am" src="https://user-images.githubusercontent.com/867334/43774419-02fce53e-9a17-11e8-83e8-ba06bd578853.png">
