### ISSUE TITLE
guided experience clean up

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#804]
see Zeplin

**Comment by maxneuvians** [comment]
<img width="791" alt="screen shot 2018-08-21 at 1 02 29 pm" src="https://user-images.githubusercontent.com/867334/44417203-e4cf1000-a542-11e8-9aee-2b9a0361d88b.png">

**Comment by sastels** [comment]
Done in several PRs over the last month.
