### ISSUE TITLE
change needs selector to checkboxes

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#805]
GE and BD

**Comment by maxneuvians** [comment]
<img width="747" alt="screen shot 2018-08-21 at 1 09 17 pm" src="https://user-images.githubusercontent.com/867334/44417427-7e96bd00-a543-11e8-8d5e-0136d171c79d.png">
<img width="254" alt="screen shot 2018-08-21 at 1 09 34 pm" src="https://user-images.githubusercontent.com/867334/44417428-7e96bd00-a543-11e8-8516-9f35fe1645fd.png">
