### ISSUE TITLE
Improve styling of reset filters button

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#820]
New Design:
![screen shot 2018-08-07 at 2 19 41 pm](https://user-images.githubusercontent.com/5498428/43794684-0cfcda2c-9a4d-11e8-887b-50524122d35d.png)

Current app:
<img width="392" alt="screen shot 2018-08-08 at 12 56 50 pm" src="https://user-images.githubusercontent.com/5498428/43852172-8e73b87e-9b0a-11e8-80ec-a9210eb5a9c4.png">

**Comment by thomascraig** [comment]
@smcmurtry was there a new design piece from the designers for this issue?

**Comment by smcmurtry** [comment]
@thomascraig I just updated my comment. The image there is the new design.

We need to change the button so that it floats right, is blue, smaller text, and has an X.
