### ISSUE TITLE
No visual indicator when tabbing goes through collapsed benefits.

### ISSUE THREAD

**Issue by danprime** [veteransaffairscanada/vac-benefits-directory#831]
When you tab through each benefits card in the benefits directory the tab highlights the Save Later, Learn More, and Expand card with the focus ring as expected.

What's not expected is that if you are tabbing through a benefits card that has access to other benefits (but is in collapsed state) you will tab through each of the collapsed benefits. The expected behaviour for a collapsed card (in my opinion) is after focusing on the expansion icon, it would tab to the *next benefit card* not internal.

To replicate:
1. Visit the directory
2. Make sure the Disability Award (or some other benefit that has related benefits) is at the top
3. Start Tabbing (note the focus ring)
4. Tab until after the "Learn more""
5. Tab once more to see the focus on the expansion bar
6. Pressing tab, will now focus on the "hidden" benefits (you will need to tab 6 times before getting to the next one).

<img width="788" alt="screen shot 2018-08-07 at 6 04 23 pm" src="https://user-images.githubusercontent.com/2610409/43805126-9862b9b4-9a6c-11e8-9bc5-3c05e5ca3fbb.png">

**Comment by sastels** [comment]
This might be a solution
https://github.com/mui-org/material-ui/issues/10569

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Screenreader Navigation](https://trello.com/c/knKtuM4T/100-accessibility-screenreader-navigation)

**Comment by smcmurtry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Keyboard Navigation](https://trello.com/c/McZemABK/99-accessibility-keyboard-navigation)

**Comment by courtneycl** [comment]
This doesn't occur anymore with the new card ui; closing.
