### ISSUE TITLE
Data Munging of Benefits Navigator Data

### ISSUE THREAD

**Issue by danprime** [veteransaffairscanada/vac-benefits-directory#84]
Objective: 
- Qualify if service status and family member type are worthwhile filters to present to users
- Qualify if applying for disability before April 2006 determines eligibility for disability benefits and other benefits

Description:
- Right now, we see how many benefits apply for a given statement. Design would like to see the results of having certain specific statements combined together.

Inquiries: 
CAF Still serving
CAF released
RCMP still serving 
RCMP released 
Family CAF
Family RCMP

Spouse CAF ?
Survivor CAF ? 
Orphan CAF ?
Applied before 2006 ?

**Comment by sastels** [comment]
According to Design this can wait until the end of the sprint.

**Comment by sastels** [comment]
https://docs.google.com/spreadsheets/d/1iCVOq76rHVCISQOeDkjQEn3Vh5S5dj7pGwy3rWYyde0/edit#gid=167338365
