### ISSUE TITLE
Landing page card a bit too wide

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#840]
Edges of card should line up with elements in top banner:
<img width="1440" alt="screen shot 2018-08-08 at 1 31 29 pm" src="https://user-images.githubusercontent.com/5498428/43854045-c8ee5aa4-9b0f-11e8-8e1b-d6e4fac19006.png">

**Comment by maxneuvians** [comment]
except on desktop it is smaller 
<img width="1471" alt="screen shot 2018-08-08 at 3 25 52 pm" src="https://user-images.githubusercontent.com/867334/43859687-61761802-9b1f-11e8-8170-a429378c97bc.png">
