### ISSUE TITLE
Map search bar on Windows too high

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#853]
Browserstack, Windows 8.1, IE 11

<img width="542" alt="image" src="https://user-images.githubusercontent.com/8228248/43865993-402fb794-9b32-11e8-815d-7c028410d17a.png">

**Comment by sastels** [comment]
note: looks fine on Windows 10, Edge

**Comment by maxneuvians** [comment]
We need to adjust this to look like all the other searches anyway
