### ISSUE TITLE
Choose between AWS and Azure

### ISSUE THREAD

**Issue by leonL** [veteransaffairscanada/vac-benefits-directory#87]
The VAC dev will be joining the project soon. We want to have one cloud service that we're showing them by then.
Do VAC preferences matter?

**Comment by szinck1** [comment]
what are their preferences? are they using any cloud tech today?

**Comment by szinck1** [comment]
I'm told AWS will be the only Cloud provider that has Protected services at least for the short-mid term.  @obrien-j can you provide more info?

**Comment by obrien-j** [comment]
We haven't done any assessments of 'protected' cloud providers. We should
take this one offline.
