### ISSUE TITLE
After searching for a benefit from homepage, results page is scrolled to the middle (mobile)

### ISSUE THREAD

**Issue by courtneycl** [veteransaffairscanada/vac-benefits-directory#870]
mobile only - desktop is fine. observed on a google pixel.

1. On the home page of the app, enter something in "Search the benefit list" that will give results, like `disability`
2. hit enter on your phone 
3. observe the resulting page is scrolled down the page - expected it would start at the top. 
![image](https://user-images.githubusercontent.com/3474250/43911461-827b42b2-9bcd-11e8-8525-76562d8ef1e9.png)

**Comment by sastels** [comment]
I can't reproduce this @sidewalkballet - can I borrow your phone?

**Comment by courtneycl** [comment]
I can't repro anymore either - closing.
