### ISSUE TITLE
Search does an "or" between words rather than an "and"

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#880]
So if you click on the autosuggestion "Disability Benefit" you also get everything that matches "Benefit"

**Comment by SupeDeDupe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make the search work for "see more" example content](https://trello.com/c/DW9nCCwM/147-make-the-search-work-for-see-more-example-content)

**Comment by sastels** [comment]
I think this specific issue was dealt with when we changed the app to rank by the search score (@smcmurtry ?)
