### ISSUE TITLE
improve e2e tests

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#906]
Testcafe / BrowserStack is a bit flakey, but not terrible. Let's build up some more tests using it.

**Comment by maxneuvians** [comment]
Bit of a blocker for print pages https://testcafe-discuss.devexpress.com/t/how-to-close-print-dialog/1107/2

**Comment by sastels** [comment]
As that link points out, though, we can mock away `window.print` so the popup won't appear. Not terrible.

**Comment by maxneuvians** [comment]
Except it does not work 😢
