### ISSUE TITLE
Confirm that language of site corresponds to browser locale

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#91]

**Comment by maxneuvians** [comment]
<img width="708" alt="screen shot 2018-04-18 at 1 23 47 pm" src="https://user-images.githubusercontent.com/867334/38947803-d8c994f4-430b-11e8-8e05-cbda3fa81f75.png">
<img width="974" alt="screen shot 2018-04-18 at 1 24 00 pm" src="https://user-images.githubusercontent.com/867334/38947809-da550268-430b-11e8-8cc9-a41ee5b67596.png">

**Comment by maxneuvians** [comment]
Cypress does not support sending Accept-Language headers so this needs to be confirmed manually.

**Comment by sastels** [comment]
👍
