### ISSUE TITLE
Spike: Investigate Strategy for Accessibility Testing

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#92]

**Comment by sastels** [comment]
See milestone issue #55 for details. 
- Make sure to get input from other members of CDS, lots to consider here in terms of what done means

**Comment by sastels** [comment]
Time boxed to a day of work for now: return to the rest of the team with a short report afterward to figure out next steps as a group.

**Comment by leonL** [comment]
Abandoned issue. The question of CDS's standards regarding accessibility QA will be taken up at the dev guild level.
