### ISSUE TITLE
Standardize how we apply css

### ISSUE THREAD

**Issue by smcmurtry** [veteransaffairscanada/vac-benefits-directory#921]
Currently we're applying css in 3 ways: using `withStyles`, using `Emotion`, and using the inline `style` attribute.

I'm not sure which way is best, but we should probably just do it one way.

We should move from defining the same css attribute in multiple places (such as the page margin) and have it defined in one place. Maybe common things should all be in `theme`?

**Comment by leonL** [comment]
Need to decide on a strategy for implementing the new pattern using Emotion, either spontaneously as inline styles are identified or as one big refactor. Wait to discuss with Adam.

**Comment by sastels** [comment]
Are we good to close this?

**Comment by smcmurtry** [comment]
I'll close this because we've now gotten rid of `withStyles` and most of our inline styling in favour of `emotion/css`. There's still more work to do to get to the point where we can apply consistent styling across our app by changing 1 variable. But that can be addressed in separate issues.
