### ISSUE TITLE
Benefit Card headers should be able to display warnings/notifications (not just 'parent' benefits)

### ISSUE THREAD

**Issue by sastels** [veteransaffairscanada/vac-benefits-directory#929]
say for Disability Award. put that text in the (!) area. Check with Design for content

**Comment by sastels** [comment]
see https://docs.google.com/document/d/1KqKzU7Nx75Nr8MISTp9kHpuoBzXeDHyuU_bi2wfAO3w/edit

**Comment by sastels** [comment]
Just for Disability Award & Pension. Content:

**Disability Award / Indemnité d'invalidité** 
Note EN: Will be replaced by Pension for Life on April 1st 2019.
Note FR:  Sera remplacé par Pension à vie le 1er avril 2019.

**Disability Pension / Pension d’invalidité** 
Note EN: Available to military members who applied before April 1st 2006. WWII, Korean War Veterans, and RCMP can apply at anytime.
Note FR:  Disponible pour les militaires qui ont postulé avant le 1er avril 2006. Les vétérans de la Seconde Guerre mondiale, de la guerre de Corée et les membres de la GRC peuvent appliquer en tout temps.

**Comment by leonL** [comment]
Important edge case to consider: what happens if a benefit has both 'parent' benefits and a warning notice?

**Comment by sastels** [comment]
@leonL Currently we aren't anticipating that to happen, but likely what we should do is just put both warnings in there (where right now one of the texts is empty)

**Comment by thomascraig** [comment]
@sastels can you share the g doc file?  I can take a look at this one.
