### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#960]
Our aim is to update all package dependencies once per sprint. Responsibility for this task is rotated through all the developers. We have come up with the following more or less sane workflow given the the Javascript ecosystem:

In a new branch

[ ] Prune things no longer needed
[ ] Run `yarn upgrade-interactive --latest --ignore-engines` to find upgraded packages
[ ] Upgrade patch and minor version changes (green and yellow)
[ ] Run tests
[ ] Commit

For each red (major version) upgrade:

[ ] Upgrade
[ ] Run tests
 Examine app locally
[ ] Commit

**Comment by thomascraig** [comment]
@maxneuvians , So in the pruning case, I would be removing just the __test__/pages/A_test.js . only, correct?

<img width="582" alt="screenshot 2018-08-21 10 34 40" src="https://user-images.githubusercontent.com/1898328/44404857-433dc380-a52e-11e8-99c2-253d4da45770.png">

**Comment by thomascraig** [comment]
and store.js ?

**Comment by maxneuvians** [comment]
@thomascraig those should all happen automatically - it is just showing you the diff between what you have locally and what you just pulled down from the repo. Store.js definitely should stay there. It just is showing that one line was removed between the version you have locally and what came from master.

**Comment by thomascraig** [comment]
ok, yeah noticed that at the bottom after I posted.  Thanks

**Comment by thomascraig** [comment]
Updates completed.
