### ISSUE TITLE
Filter eligibilityPaths when they are invalid

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#966]
see #965 

Maybe also filter all data when not valid?

**Comment by sastels** [comment]
We should ensure that 
* the app works as expected when there's bad data, and
* the bad data is flagged in the data-validation page

**Comment by smcmurtry** [comment]
I'm not sure what the rules should be for detecting all kinds of invalid data, but one easy thing to detect is if the data is missing. I've created an issue for this: #1084

**Comment by sastels** [comment]
Right now we check for "na" in a path and if so match any profile selection. We should probably also match anything for `undefined`.
https://github.com/cds-snc/vac-benefits-directory/blob/master/selectors/benefits.js#L66

**Comment by sastels** [comment]
Closed by #1088 and #1089
