### ISSUE TITLE
Use <h1> and <h2> elements for page title and some other headings

### ISSUE THREAD

**Issue by maxneuvians** [veteransaffairscanada/vac-benefits-directory#980]
Use `<h1>` and `<h2>` elements for page title and some other headings rather than the material-ui Typography components. This helps screen readers know what the headings are.

See #380

**Comment by smcmurtry** [comment]
Here are some guidelines for how to use heading elements:
https://www.w3.org/WAI/tutorials/page-structure/headings/
http://www.bbc.co.uk/guidelines/futuremedia/technical/semantic_markup.shtml#headings

**Comment by maxneuvians** [comment]
Closed in #989
